import type { ArenaProfile } from "../../domain/arena/arenaTypes";
import { validateArenaDefinition } from "../../domain/arena/arenaValidation";
import { auditChangedFiles, captureWorkspaceState, resolveWorkspacePath } from "../../infrastructure/files/changedFileAudit";
import { formatJson } from "../../infrastructure/files/jsonFileStore";
import { createFileSnapshot, type CreatedSnapshot } from "../../infrastructure/snapshots/fileSnapshotStore";
import { ErrorCodes } from "../../shared/errorCodes";
import { operationResult, type OperationError, type OperationResult } from "../../shared/operationResult";
import { transactionalFileReplace, type ContentVerification, type TransactionalFileReplaceDependencies, type TransactionalReplaceFailure } from "../persistence/transactionalFileReplace";
import { withTargetOperationLock } from "../persistence/targetOperationLock";
import { isLoadedArena, loadValidArena } from "./arenaOperationSupport";

export interface SetArenaValueDependencies { createSnapshot: typeof createFileSnapshot; transaction: Partial<TransactionalFileReplaceDependencies>; verifyContent: (content: string) => ContentVerification<ArenaProfile> }
const productionDependencies: SetArenaValueDependencies = { createSnapshot: createFileSnapshot, transaction: {}, verifyContent: verifyArenaContent };

export async function setArenaValue(workspaceRoot: string, inputFile: string, propertyPath: string, value: unknown, dryRun: boolean, injected: Partial<SetArenaValueDependencies> = {}): Promise<OperationResult> { const dependencies = { ...productionDependencies, ...injected, transaction: { ...productionDependencies.transaction, ...injected.transaction } }; if (dryRun) return executeSet(workspaceRoot, inputFile, propertyPath, value, true, dependencies); let relativePath: string; try { relativePath = resolveWorkspacePath(workspaceRoot, inputFile).relativePath; } catch (caught) { return operationResult({ command: "arena.set", status: "failed", input: { file: inputFile, propertyPath, value, dryRun }, errors: [{ code: ErrorCodes.ArenaWriteBlocked, path: inputFile, message: caught instanceof Error ? caught.message : String(caught) }] }); } return withTargetOperationLock(workspaceRoot, relativePath, () => executeSet(workspaceRoot, inputFile, propertyPath, value, false, dependencies)); }

async function executeSet(workspaceRoot: string, inputFile: string, propertyPath: string, value: unknown, dryRun: boolean, dependencies: SetArenaValueDependencies): Promise<OperationResult> {
  const command = "arena.set"; const input = { file: inputFile, propertyPath, value, dryRun }; const before = await captureWorkspaceState(workspaceRoot); const loaded = await loadValidArena(workspaceRoot, inputFile); if (!isLoadedArena(loaded)) return operationResult({ command, status: "failed", input, errors: loaded.errors });
  const candidate = structuredClone(loaded.profile) as ArenaProfile; const pathError = applyExistingProperty(candidate, propertyPath, value); if (pathError) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: [pathError] });
  const validation = validateArenaDefinition(candidate); if (!validation.valid || validation.profile === null) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: validation.errors.map((error) => error.code === ErrorCodes.ArenaSchemaInvalid ? { ...error, code: ErrorCodes.ArenaPropertyValueInvalid } : error) });
  if (dryRun) { const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); if (!audit.ok) return operationResult({ command, status: "failed", input, errors: [{ code: ErrorCodes.ArenaWriteScopeAuditFailed, message: "Arena dry run changed files outside its zero-write scope", details: { unexpectedFiles: audit.unexpectedFiles } }], changedFiles: audit.changedFiles }); return operationResult({ command, status: "dry_run", input: { ...input, file: loaded.relativePath }, data: { profile: validation.profile, proposedChange: { path: propertyPath, value } } }); }
  let snapshot: CreatedSnapshot; try { snapshot = await dependencies.createSnapshot(workspaceRoot, loaded.relativePath, loaded.content, command, "arena-profile"); } catch (caught) { const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: [{ code: ErrorCodes.ArenaWriteBlocked, path: loaded.relativePath, message: `Pre-write snapshot could not be created: ${caught instanceof Error ? caught.message : String(caught)}` }], changedFiles: audit.changedFiles }); }
  const transaction = await transactionalFileReplace({ workspaceRoot, operationStartState: before, targetAbsolutePath: loaded.absolutePath, targetRelativePath: loaded.relativePath, replacementContent: formatJson(validation.profile), originalContent: loaded.content, allowedPaths: [loaded.relativePath, snapshot.relativePath], verifyContent: dependencies.verifyContent, dependencies: dependencies.transaction }); if (!transaction.ok) return transactionFailure(command, { ...input, file: loaded.relativePath }, transaction, snapshot.record.snapshotId); return operationResult({ command, status: "passed", input: { ...input, file: loaded.relativePath }, data: { profile: transaction.value, appliedChange: { path: propertyPath, value } }, changedFiles: transaction.changedFiles, snapshotId: snapshot.record.snapshotId });
}

export function verifyArenaContent(content: string): ContentVerification<ArenaProfile> { let value: unknown; try { value = JSON.parse(content) as unknown; } catch { return { validationPassed: false, errors: [{ code: ErrorCodes.ArenaJsonInvalid, message: "Persisted arena content is not valid JSON" }] }; } const validation = validateArenaDefinition(value); return validation.valid && validation.profile ? { validationPassed: true, value: validation.profile } : { validationPassed: false, errors: validation.errors }; }
function transactionFailure(command: string, input: Record<string, unknown>, transaction: TransactionalReplaceFailure, snapshotId: string): OperationResult { const errors: OperationError[] = [{ code: transaction.failureStage === "scope_audit" ? ErrorCodes.ArenaWriteScopeAuditFailed : ErrorCodes.ArenaWriteVerificationFailed, message: transaction.failureMessage, details: { failureStage: transaction.failureStage, unexpectedFiles: transaction.unexpectedFiles, verificationErrors: transaction.verificationErrors } }]; if (transaction.recovery.status === "failed") errors.push({ code: ErrorCodes.ArenaWriteRecoveryFailed, path: transaction.recovery.restoredFile, message: "Arena write recovery could not verify the exact original target state", details: { recovery: transaction.recovery } }); return operationResult({ command, status: "failed", input, data: { failureStage: transaction.failureStage, recovery: transaction.recovery }, errors, changedFiles: transaction.changedFiles, snapshotId }); }

function applyExistingProperty(profile: ArenaProfile, propertyPath: string, value: unknown): OperationError | null { const segments = propertyPath.split("."); if (!propertyPath || segments.some((segment) => !segment || ["__proto__", "prototype", "constructor"].includes(segment))) return notFound(propertyPath); let current: unknown = profile; for (const segment of segments.slice(0, -1)) { if (!record(current) || !Object.prototype.hasOwnProperty.call(current, segment)) return notFound(propertyPath); current = current[segment]; } const leaf = segments.at(-1) as string; if (!record(current) || !Object.prototype.hasOwnProperty.call(current, leaf)) return notFound(propertyPath); current[leaf] = value; return null; }
function notFound(path: string): OperationError { return { code: ErrorCodes.ArenaPropertyNotFound, path, message: "Only existing schema-defined arena properties may be edited" }; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
