import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { setCameraValue, verifyCameraContent } from "../src/application/camera/setCameraValue";
import type { CameraProfile } from "../src/domain/camera/cameraTypes";
import { atomicWriteText } from "../src/infrastructure/files/jsonFileStore";
import { listSnapshotSummaries } from "../src/infrastructure/snapshots/fileSnapshotStore";
import { ErrorCodes } from "../src/shared/errorCodes";
import { createCameraTestWorkspace } from "./testUtils";

test("camera set dry run validates candidate and changes zero files", async (context) => { const workspace = await createCameraTestWorkspace(context); const original = await readFile(workspace.cameraFile, "utf8"); const result = await setCameraValue(workspace.root, workspace.relativeFile, "orbit.yawSpeedDegreesPerSecond", 200, true); assert.equal(result.status, "dry_run"); assert.deepEqual(result.changedFiles, []); assert.equal(await readFile(workspace.cameraFile, "utf8"), original); assert.equal((await listSnapshotSummaries(workspace.root)).length, 0); });
test("camera set persists valid property and creates kind-aware snapshot", async (context) => { const workspace = await createCameraTestWorkspace(context); const result = await setCameraValue(workspace.root, workspace.relativeFile, "orbit.yawSpeedDegreesPerSecond", 200, false); assert.equal(result.status, "passed"); assert(result.changedFiles.includes(workspace.relativeFile)); assert(result.changedFiles.some((file) => file.startsWith(".mam-engine/snapshots/"))); const profile = JSON.parse(await readFile(workspace.cameraFile, "utf8")) as CameraProfile; assert.equal(profile.orbit.yawSpeedDegreesPerSecond, 200); assert.equal((await listSnapshotSummaries(workspace.root))[0]?.definitionKind, "camera-profile"); });
test("camera set rejects unknown property and invalid value", async (context) => { const workspace = await createCameraTestWorkspace(context); assert.equal((await setCameraValue(workspace.root, workspace.relativeFile, "orbit.missing", 1, false)).errors[0]?.code, ErrorCodes.CameraPropertyNotFound); assert.equal((await setCameraValue(workspace.root, workspace.relativeFile, "orbit.yawSpeedDegreesPerSecond", "fast", false)).errors[0]?.code, ErrorCodes.CameraPropertyValueInvalid); });
test("semantic camera invalidity performs zero target writes", async (context) => { const workspace = await createCameraTestWorkspace(context); const original = await readFile(workspace.cameraFile, "utf8"); const result = await setCameraValue(workspace.root, workspace.relativeFile, "collision.minimumDistance", 99, false); assert.equal(result.status, "failed"); assert.equal(await readFile(workspace.cameraFile, "utf8"), original); assert.equal((await listSnapshotSummaries(workspace.root)).length, 0); });
test("camera post-write failure restores exact original content", async (context) => { const workspace = await createCameraTestWorkspace(context); const original = await readFile(workspace.cameraFile, "utf8"); let validations = 0; const result = await setCameraValue(workspace.root, workspace.relativeFile, "orbit.yawSpeedDegreesPerSecond", 200, false, { verifyContent: (content) => { validations += 1; return validations === 1 ? { validationPassed: false } : verifyCameraContent(content); } }); assert.equal(result.status, "failed"); assert.equal((result.data as { recovery: { status: string } }).recovery.status, "restored"); assert.equal(await readFile(workspace.cameraFile, "utf8"), original); });
test("same-target camera writes serialize", async (context) => {
  const workspace = await createCameraTestWorkspace(context); let active = 0; let maximum = 0;
  const delayed = async (filePath: string, content: string) => { active += 1; maximum = Math.max(maximum, active); await new Promise((resolve) => setTimeout(resolve, 20)); await atomicWriteText(filePath, content); active -= 1; };
  const [first, second] = await Promise.all([setCameraValue(workspace.root, workspace.relativeFile, "orbit.yawSpeedDegreesPerSecond", 190, false, { transaction: { writeText: delayed } }), setCameraValue(workspace.root, workspace.relativeFile, "orbit.yawSpeedDegreesPerSecond", 200, false, { transaction: { writeText: delayed } })]);
  assert.equal(first.status, "passed"); assert.equal(second.status, "passed"); assert.equal(maximum, 1); assert.equal((JSON.parse(await readFile(workspace.cameraFile, "utf8")) as CameraProfile).orbit.yawSpeedDegreesPerSecond, 200);
});
test("camera persistent set allows only target and snapshot paths", async (context) => { const workspace = await createCameraTestWorkspace(context); const result = await setCameraValue(workspace.root, workspace.relativeFile, "lens.fieldOfViewDegrees", 70, false); assert.equal(result.status, "passed"); assert(result.changedFiles.every((file) => file === workspace.relativeFile || file.startsWith(".mam-engine/snapshots/"))); });
