import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { setCameraValue } from "../src/application/camera/setCameraValue";
import { validateDefinition } from "../src/application/definitions/definitionValidationRegistry";
import { setMovementValue } from "../src/application/movement/setMovementValue";
import { createSnapshot } from "../src/application/snapshots/createSnapshot";
import { rollbackSnapshot } from "../src/application/snapshots/rollbackSnapshot";
import { createFileSnapshot, listSnapshotSummaries } from "../src/infrastructure/snapshots/fileSnapshotStore";
import { ErrorCodes } from "../src/shared/errorCodes";
import { createCameraTestWorkspace, defaultCameraProfile, defaultProfile } from "./testUtils";

test("definition registry recognizes movement and camera profiles", async () => { const movement = validateDefinition(await defaultProfile()); const camera = validateDefinition(await defaultCameraProfile()); assert.equal(movement.kind, "movement-profile"); assert.equal(movement.valid, true); assert.equal(camera.kind, "camera-profile"); assert.equal(camera.valid, true); });
test("definition registry rejects unknown kinds", () => { const result = validateDefinition({ schemaVersion: 1, kind: "arbitrary" }); assert.equal(result.valid, false); assert.equal(result.errors[0]?.code, ErrorCodes.DefinitionKindUnsupported); });
test("camera snapshot create succeeds with definition-kind metadata", async (context) => { const workspace = await createCameraTestWorkspace(context); const result = await createSnapshot(workspace.root, workspace.relativeFile); assert.equal(result.status, "passed"); assert.equal((result.data as { snapshot: { definitionKind: string } }).snapshot.definitionKind, "camera-profile"); assert.equal((await listSnapshotSummaries(workspace.root))[0]?.definitionKind, "camera-profile"); });
test("legacy movement snapshots without kind metadata remain rollback-compatible", async (context) => { const workspace = await createCameraTestWorkspace(context); const original = await readFile(workspace.movementFile, "utf8"); const legacy = await createFileSnapshot(workspace.root, workspace.movementRelativeFile, original, "legacy-test"); assert.equal(legacy.record.definitionKind, undefined); await setMovementValue(workspace.root, workspace.movementRelativeFile, "ground.runSpeed", 6.5, false); const result = await rollbackSnapshot(workspace.root, legacy.record.snapshotId); assert.equal(result.status, "rolled_back"); assert.equal(await readFile(workspace.movementFile, "utf8"), original); });
test("camera rollback creates safety snapshot and is reversible", async (context) => { const workspace = await createCameraTestWorkspace(context); const original = await readFile(workspace.cameraFile, "utf8"); const set = await setCameraValue(workspace.root, workspace.relativeFile, "orbit.yawSpeedDegreesPerSecond", 200, false); const updated = await readFile(workspace.cameraFile, "utf8"); const first = await rollbackSnapshot(workspace.root, set.snapshotId as string); assert.equal(first.status, "rolled_back"); assert.equal(await readFile(workspace.cameraFile, "utf8"), original); const data = first.data as { sourceSnapshotId: string; preRollbackSnapshotId: string }; assert.equal(data.sourceSnapshotId, set.snapshotId); assert.equal(data.preRollbackSnapshotId, first.snapshotId); const second = await rollbackSnapshot(workspace.root, first.snapshotId as string); assert.equal(second.status, "rolled_back"); assert.equal(await readFile(workspace.cameraFile, "utf8"), updated); });
test("movement snapshot cannot overwrite camera target", async (context) => { const workspace = await createCameraTestWorkspace(context); const cameraBefore = await readFile(workspace.cameraFile, "utf8"); const movementContent = await readFile(workspace.movementFile, "utf8"); const snapshot = await createFileSnapshot(workspace.root, workspace.relativeFile, movementContent, "cross-kind", "movement-profile"); const count = (await listSnapshotSummaries(workspace.root)).length; const result = await rollbackSnapshot(workspace.root, snapshot.record.snapshotId); assert.equal(result.status, "failed"); assert.equal(result.errors[0]?.code, ErrorCodes.SnapshotRollbackFailed); assert.equal(await readFile(workspace.cameraFile, "utf8"), cameraBefore); assert.equal((await listSnapshotSummaries(workspace.root)).length, count); assert.deepEqual(result.changedFiles, []); });
test("camera snapshot cannot overwrite movement target", async (context) => { const workspace = await createCameraTestWorkspace(context); const movementBefore = await readFile(workspace.movementFile, "utf8"); const cameraContent = await readFile(workspace.cameraFile, "utf8"); const snapshot = await createFileSnapshot(workspace.root, workspace.movementRelativeFile, cameraContent, "cross-kind", "camera-profile"); const count = (await listSnapshotSummaries(workspace.root)).length; const result = await rollbackSnapshot(workspace.root, snapshot.record.snapshotId); assert.equal(result.status, "failed"); assert.equal(await readFile(workspace.movementFile, "utf8"), movementBefore); assert.equal((await listSnapshotSummaries(workspace.root)).length, count); assert.deepEqual(result.changedFiles, []); });
