import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { validateDefinition } from "../src/application/definitions/definitionValidationRegistry";
import { createSnapshot } from "../src/application/snapshots/createSnapshot";
import { rollbackSnapshot } from "../src/application/snapshots/rollbackSnapshot";
import { setTargetingValue } from "../src/application/targeting/setTargetingValue";
import { createFileSnapshot, listSnapshotSummaries } from "../src/infrastructure/snapshots/fileSnapshotStore";
import { ErrorCodes } from "../src/shared/errorCodes";
import { createTargetingTestWorkspace, defaultTargetingProfile } from "./testUtils";

test("definition registry recognizes targeting profile and expected kind list includes it", async () => { const result = validateDefinition(await defaultTargetingProfile()); assert.equal(result.valid, true); assert.equal(result.kind, "targeting-profile"); const unsupported = validateDefinition({ schemaVersion: 1, kind: "other" }); assert.deepEqual(unsupported.errors[0]?.expected, ["movement-profile", "camera-profile", "targeting-profile", "defensive-action-profile", "offensive-action-profile"]); });
test("targeting snapshot creation records definition kind", async (context) => { const workspace = await createTargetingTestWorkspace(context); const result = await createSnapshot(workspace.root, workspace.relativeFile); assert.equal(result.status, "passed"); assert.equal((result.data as any).snapshot.definitionKind, "targeting-profile"); assert.equal((await listSnapshotSummaries(workspace.root))[0]?.definitionKind, "targeting-profile"); });
test("targeting rollback creates safety snapshot and is reversible", async (context) => { const workspace = await createTargetingTestWorkspace(context); const original = await readFile(workspace.targetingFile, "utf8"); const set = await setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.maximumDistance", 35, false); const updated = await readFile(workspace.targetingFile, "utf8"); const first = await rollbackSnapshot(workspace.root, set.snapshotId as string); assert.equal(first.status, "rolled_back"); assert.equal(await readFile(workspace.targetingFile, "utf8"), original); assert.equal((first.data as any).definitionKind, "targeting-profile"); const second = await rollbackSnapshot(workspace.root, first.snapshotId as string); assert.equal(second.status, "rolled_back"); assert.equal(await readFile(workspace.targetingFile, "utf8"), updated); });
test("movement and camera snapshots cannot overwrite targeting", async (context) => { const workspace = await createTargetingTestWorkspace(context); const before = await readFile(workspace.targetingFile, "utf8"); for (const [kind, source] of [["movement-profile", workspace.movementFile], ["camera-profile", workspace.cameraFile]] as const) { const snapshot = await createFileSnapshot(workspace.root, workspace.relativeFile, await readFile(source, "utf8"), "cross-kind", kind); const result = await rollbackSnapshot(workspace.root, snapshot.record.snapshotId); assert.equal(result.status, "failed"); assert.equal(result.errors[0]?.code, ErrorCodes.SnapshotRollbackFailed); assert.equal(await readFile(workspace.targetingFile, "utf8"), before); assert.deepEqual(result.changedFiles, []); } });
test("targeting snapshot cannot overwrite movement or camera", async (context) => { const workspace = await createTargetingTestWorkspace(context); const targeting = await readFile(workspace.targetingFile, "utf8"); for (const [target, relative] of [[workspace.movementFile, workspace.movementRelativeFile], [workspace.cameraFile, workspace.cameraRelativeFile]] as const) { const before = await readFile(target, "utf8"); const snapshot = await createFileSnapshot(workspace.root, relative, targeting, "cross-kind", "targeting-profile"); const result = await rollbackSnapshot(workspace.root, snapshot.record.snapshotId); assert.equal(result.status, "failed"); assert.equal(await readFile(target, "utf8"), before); assert.deepEqual(result.changedFiles, []); } });
