import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { setTargetingValue, verifyTargetingContent } from "../src/application/targeting/setTargetingValue";
import type { TargetingProfile } from "../src/domain/targeting/targetingTypes";
import { auditChangedFiles } from "../src/infrastructure/files/changedFileAudit";
import { atomicWriteText } from "../src/infrastructure/files/jsonFileStore";
import { listSnapshotSummaries } from "../src/infrastructure/snapshots/fileSnapshotStore";
import { ErrorCodes } from "../src/shared/errorCodes";
import { createTargetingTestWorkspace } from "./testUtils";

test("targeting set dry run validates candidate without writes or snapshots", async (context) => { const workspace = await createTargetingTestWorkspace(context); const original = await readFile(workspace.targetingFile, "utf8"); const result = await setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.maximumDistance", 35, true); assert.equal(result.status, "dry_run"); assert.deepEqual(result.changedFiles, []); assert.equal(await readFile(workspace.targetingFile, "utf8"), original); assert.equal((await listSnapshotSummaries(workspace.root)).length, 0); });
test("targeting set persists valid property with exact kind-aware snapshot", async (context) => { const workspace = await createTargetingTestWorkspace(context); const original = await readFile(workspace.targetingFile, "utf8"); const result = await setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.maximumDistance", 35, false); assert.equal(result.status, "passed"); const profile = JSON.parse(await readFile(workspace.targetingFile, "utf8")) as TargetingProfile; assert.equal(profile.acquisition.maximumDistance, 35); const snapshots = await listSnapshotSummaries(workspace.root); assert.equal(snapshots[0]?.definitionKind, "targeting-profile"); assert.notEqual(await readFile(workspace.targetingFile, "utf8"), original); assert(result.changedFiles.every((file) => file === workspace.relativeFile || file.startsWith(".mam-engine/snapshots/"))); });
test("targeting set rejects nonexistent property and invalid candidate value", async (context) => { const workspace = await createTargetingTestWorkspace(context); assert.equal((await setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.missing", 1, false)).errors[0]?.code, ErrorCodes.TargetingPropertyNotFound); assert.equal((await setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.maximumDistance", "far", false)).errors[0]?.code, ErrorCodes.TargetingPropertyValueInvalid); });
test("semantic targeting invalidity performs zero writes", async (context) => { const workspace = await createTargetingTestWorkspace(context); const original = await readFile(workspace.targetingFile, "utf8"); const result = await setTargetingValue(workspace.root, workspace.relativeFile, "retention.maximumDistanceMultiplier", 0.5, false); assert.equal(result.status, "failed"); assert.equal(await readFile(workspace.targetingFile, "utf8"), original); assert.equal((await listSnapshotSummaries(workspace.root)).length, 0); });
test("targeting post-write verification failure restores exact content", async (context) => { const workspace = await createTargetingTestWorkspace(context); const original = await readFile(workspace.targetingFile, "utf8"); let validations = 0; const result = await setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.maximumDistance", 35, false, { verifyContent: (content) => { validations += 1; return validations === 1 ? { validationPassed: false } : verifyTargetingContent(content); } }); assert.equal(result.status, "failed"); assert.equal((result.data as any).recovery.status, "restored"); assert.equal(await readFile(workspace.targetingFile, "utf8"), original); });
test("targeting scope audit failure restores exact content", async (context) => { const workspace = await createTargetingTestWorkspace(context); const original = await readFile(workspace.targetingFile, "utf8"); let audits = 0; const result = await setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.maximumDistance", 35, false, { transaction: { audit: (before, after, allowed) => { audits += 1; return audits === 1 ? { ok: false, changedFiles: [...allowed], unexpectedFiles: ["unexpected.txt"] } : auditChangedFiles(before, after, allowed); } } }); assert.equal(result.errors[0]?.code, ErrorCodes.TargetingWriteScopeAuditFailed); assert.equal((result.data as any).recovery.status, "restored"); assert.equal(await readFile(workspace.targetingFile, "utf8"), original); });
test("same-target targeting writes serialize", async (context) => { const workspace = await createTargetingTestWorkspace(context); let active = 0; let maximum = 0; const delayed = async (filePath: string, content: string) => { active += 1; maximum = Math.max(maximum, active); await new Promise((resolve) => setTimeout(resolve, 20)); await atomicWriteText(filePath, content); active -= 1; }; const [first, second] = await Promise.all([setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.maximumDistance", 31, false, { transaction: { writeText: delayed } }), setTargetingValue(workspace.root, workspace.relativeFile, "acquisition.maximumDistance", 32, false, { transaction: { writeText: delayed } })]); assert.equal(first.status, "passed"); assert.equal(second.status, "passed"); assert.equal(maximum, 1); assert.equal((JSON.parse(await readFile(workspace.targetingFile, "utf8")) as TargetingProfile).acquisition.maximumDistance, 32); });
