import assert from "node:assert/strict";
import test from "node:test";

import { buildTargetingRuntimePlan, type TargetingRuntimeScenario } from "../src/domain/runtime/targetingRuntimePlan";
import { simulateTargetingRuntime } from "../src/domain/runtime/targetingRuntimeSimulation";
import { defaultCameraProfile, defaultTargetingProfile } from "./testUtils";

const scenarios: TargetingRuntimeScenario[] = ["acquire", "eligibility", "tie-break", "retention", "loss", "reacquire", "switch-left", "switch-right", "switch-cooldown", "framing-acquire", "framing-switch", "framing-loss", "framing-reacquire"];
test("all thirteen targeting runtime simulations are deterministic", async () => { const targeting = await defaultTargetingProfile(); const camera = await defaultCameraProfile(); for (const scenario of scenarios) { const plan = buildTargetingRuntimePlan(targeting, scenario); assert.deepEqual(simulateTargetingRuntime(targeting, camera, plan), simulateTargetingRuntime(targeting, camera, plan), scenario); } });
test("runtime acquisition, eligibility, tie, retention, loss, and reacquisition match authored rules", async () => { const targeting = await defaultTargetingProfile(); const camera = await defaultCameraProfile(); const run = (scenario: TargetingRuntimeScenario, profile = targeting) => simulateTargetingRuntime(profile, camera, buildTargetingRuntimePlan(profile, scenario)).metrics; assert.notEqual(run("acquire").finalTargetId, null); const eligibility = run("eligibility").candidateEvaluations as any[]; assert(eligibility.find((item) => item.id === "blocked").rejectionCodes.includes("TARGET_LINE_OF_SIGHT_BLOCKED")); assert(eligibility.find((item) => item.id === "overlap").rejectionCodes.includes("TARGET_DIRECTION_UNDEFINED")); assert.equal(run("tie-break").finalTargetId, "alpha"); assert.equal(run("retention").finalTargetId, "current"); assert.equal(run("loss").finalTargetId, null); assert.equal(run("reacquire").finalTargetId, "replacement"); const disabled = { ...targeting, retention: { ...targeting.retention, autoReacquire: false } }; assert.equal(run("reacquire", disabled).finalTargetId, null); const zero = { ...targeting, retention: { ...targeting.retention, autoReacquire: false, lostTargetGraceSeconds: 0 } }; assert.equal(run("loss", zero).releaseStep, 1); });
test("runtime switching handles wraparound and cooldown", async () => { const targeting = await defaultTargetingProfile(); const camera = await defaultCameraProfile(); const metrics = (scenario: TargetingRuntimeScenario) => simulateTargetingRuntime(targeting, camera, buildTargetingRuntimePlan(targeting, scenario)).metrics; assert.equal(metrics("switch-left").finalTargetId, "left-wrap"); assert.equal(metrics("switch-right").finalTargetId, "right-wrap"); const requests = metrics("switch-cooldown").switchRequests as any[]; assert.equal(requests[0].reason, "cooldown_active"); assert.equal(requests.at(-1).reason, "switched"); });
test("framing converges, switches smoothly, freezes after loss, and transitions after reacquisition", async () => { const targeting = await defaultTargetingProfile(); const camera = await defaultCameraProfile(); const metrics = (scenario: TargetingRuntimeScenario, cameraProfile = camera) => simulateTargetingRuntime(targeting, cameraProfile, buildTargetingRuntimePlan(targeting, scenario)).metrics; const acquire = metrics("framing-acquire"); assert(Number(acquire.finalFramingAngularErrorDegrees) < Number(acquire.initialFramingAngularErrorDegrees)); const switched = metrics("framing-switch"); assert.equal(switched.finalTargetId, "left"); assert(Number(switched.framingActivePhysicsSteps) > 0); const loss = metrics("framing-loss"); assert.equal(loss.framingActive, false); assert.equal(loss.cameraTranslationAfterRelease, 0); assert.equal(loss.cameraAngularMovementAfterReleaseDegrees, 0); const reacquire = metrics("framing-reacquire"); assert.equal(reacquire.finalTargetId, "replacement"); assert.equal(reacquire.framingActive, true); });
test("zero camera half-lives snap and pitch remains clamped across yaw wrap", async () => { const targeting = await defaultTargetingProfile(); const camera = await defaultCameraProfile(); camera.follow.positionHalfLifeSeconds = 0; camera.follow.rotationHalfLifeSeconds = 0; const snapped = simulateTargetingRuntime(targeting, camera, buildTargetingRuntimePlan(targeting, "framing-switch")).metrics; assert(Number(snapped.finalFramingAngularErrorDegrees) < 0.001); const clampedCamera = structuredClone(camera); clampedCamera.orbit.minimumPitchDegrees = -5; clampedCamera.orbit.maximumPitchDegrees = 5; const clamped = simulateTargetingRuntime(targeting, clampedCamera, buildTargetingRuntimePlan(targeting, "framing-switch")).metrics; assert(Number(clamped.finalCameraPitchDegrees) >= -5 && Number(clamped.finalCameraPitchDegrees) <= 5); assert(Number.isFinite(Number(clamped.finalCameraYawDegrees))); });
