import assert from "node:assert/strict";
import test from "node:test";

import { validateTargetingContext, validateTargetingDefinition } from "../src/domain/targeting/targetingValidation";
import { defaultTargetingProfile } from "./testUtils";

test("valid default targeting profile satisfies schema and semantics", async () => assert.equal(validateTargetingDefinition(await defaultTargetingProfile()).valid, true));
test("targeting schema rejects missing and unknown fields at every object level", async () => { const missing: any = await defaultTargetingProfile(); delete missing.acquisition.maximumDistance; assert.equal(validateTargetingDefinition(missing).valid, false); for (const path of ["root", "acquisition", "scoring", "retention", "switching"] as const) { const value: any = await defaultTargetingProfile(); if (path === "root") value.unknown = true; else value[path].unknown = true; assert.equal(validateTargetingDefinition(value).valid, false, path); } });
test("targeting rejects unsupported schema version before schema validation", async () => { const value: any = await defaultTargetingProfile(); value.schemaVersion = 2; const result = validateTargetingDefinition(value); assert.equal(result.valid, false); assert.equal(result.errors[0]?.code, "TARGETING_SCHEMA_VERSION_UNSUPPORTED"); });
test("targeting rejects acquisition ranges and non-finite values", async () => { for (const [field, invalid] of [["maximumDistance", 0], ["maximumAngleDegrees", 0], ["maximumAngleDegrees", 181], ["maximumDistance", Number.NaN]] as const) { const value: any = await defaultTargetingProfile(); value.acquisition[field] = invalid; assert.equal(validateTargetingDefinition(value).valid, false); } });
test("targeting rejects invalid scoring weights, low/high sums, and all-zero weights", async () => { const variants = [{ distanceWeight: -0.1, angleWeight: 1, priorityWeight: 0.1 }, { distanceWeight: 0.4, angleWeight: 0.4, priorityWeight: 0.1 }, { distanceWeight: 0.5, angleWeight: 0.5, priorityWeight: 0.1 }, { distanceWeight: 0, angleWeight: 0, priorityWeight: 0 }]; for (const scoring of variants) { const value = await defaultTargetingProfile(); value.scoring = scoring; assert.equal(validateTargetingDefinition(value).valid, false); } });
test("targeting rejects invalid retention and switching configuration", async () => { const retention: any = await defaultTargetingProfile(); retention.retention.maximumDistanceMultiplier = 0.9; retention.retention.additionalAngleDegrees = 121; retention.retention.lostTargetGraceSeconds = -1; assert.equal(validateTargetingDefinition(retention).valid, false); const switching: any = await defaultTargetingProfile(); switching.switching.cooldownSeconds = -1; switching.switching.maximumAngleDegrees = 181; switching.switching.minimumSeparationDegrees = 181; assert.equal(validateTargetingDefinition(switching).valid, false); });
test("targeting context validates vectors, forward, IDs, uniqueness, and priority", () => { const result = validateTargetingContext({ origin: { x: Number.NaN, y: 0, z: 0 }, viewForward: { x: 0, y: 0, z: 0 }, currentTargetId: null, candidates: [{ id: "", targetPoint: { x: 0, y: 0, z: -1 }, targetable: true, lineOfSight: true, priority: 2 }, { id: "", targetPoint: { x: 0, y: 0, z: -2 }, targetable: true, lineOfSight: true, priority: 0 }] }); assert(result.length >= 5); });
