import assert from "node:assert/strict";
import test from "node:test";

import { acquireTarget, evaluateCandidate, runRetentionSequence, simulateTargeting, switchTarget, TARGETING_FIXED_DELTA_SECONDS } from "../src/domain/targeting/targetingSimulation";
import type { TargetCandidate, TargetingContext, TargetingProfile } from "../src/domain/targeting/targetingTypes";
import { defaultTargetingProfile } from "./testUtils";

function candidate(id: string, yaw: number, distance: number, priority = 0.5): TargetCandidate { const radians = yaw * Math.PI / 180; return { id, targetPoint: { x: -Math.sin(radians) * distance, y: 0, z: -Math.cos(radians) * distance }, targetable: true, lineOfSight: true, priority }; }
function context(candidates: TargetCandidate[], currentTargetId: string | null = null): TargetingContext { return { origin: { x: 0, y: 0, z: 0 }, viewForward: { x: 0, y: 0, z: -1 }, candidates, currentTargetId }; }
function weighted(profile: TargetingProfile, distanceWeight: number, angleWeight: number, priorityWeight: number): TargetingProfile { return { ...profile, scoring: { distanceWeight, angleWeight, priorityWeight } }; }

test("acquisition selects highest score and exposes component contributions", async () => { const profile = await defaultTargetingProfile(); const candidates = [candidate("near", 0, 5, 0), candidate("priority", 0, 20, 1), candidate("angle", 30, 5, 0)]; assert.equal(acquireTarget(weighted(profile, 1, 0, 0), context(candidates)).selectedTargetId, "near"); assert.equal(acquireTarget(weighted(profile, 0, 1, 0), context(candidates)).selectedTargetId, "near"); assert.equal(acquireTarget(weighted(profile, 0, 0, 1), context(candidates)).selectedTargetId, "priority"); const evaluation = evaluateCandidate(profile, context(candidates), candidates[0] as TargetCandidate); assert.notEqual(evaluation.distanceScore, null); assert.notEqual(evaluation.angleScore, null); assert.notEqual(evaluation.totalScore, null); });
test("eligibility rejects distance, angle, line of sight, targetability, and origin overlap", async () => { const profile = await defaultTargetingProfile(); const values = [candidate("far", 0, 31), candidate("wide", 70, 10), { ...candidate("blocked", 0, 10), lineOfSight: false }, { ...candidate("off", 0, 10), targetable: false }, { ...candidate("origin", 0, 1), targetPoint: { x: 0, y: 0, z: 0 } }]; const codes = acquireTarget(profile, context(values)).evaluations.flatMap((item) => item.rejectionCodes); for (const code of ["TARGET_OUT_OF_DISTANCE", "TARGET_OUT_OF_ANGLE", "TARGET_LINE_OF_SIGHT_BLOCKED", "TARGET_NOT_TARGETABLE", "TARGET_DIRECTION_UNDEFINED"]) assert(codes.includes(code as any), code); });
test("tie-breaking is deterministic and independent of candidate order", async () => { const profile = await defaultTargetingProfile(); const left = candidate("zeta", 10, 12); const right = candidate("alpha", 10, 12); assert.equal(acquireTarget(profile, context([left, right])).selectedTargetId, "alpha"); assert.equal(acquireTarget(profile, context([right, left])).selectedTargetId, "alpha"); });
test("tie-breaking prefers smaller angle then distance before ordinal ID", async () => { const profile = weighted(await defaultTargetingProfile(), 0, 0, 1); const candidates = [candidate("wide", 20, 10, 0.5), candidate("center-far", 0, 12, 0.5), candidate("center-near", 0, 10, 0.5)]; assert.equal(acquireTarget(profile, context(candidates)).selectedTargetId, "center-near"); });
test("retention keeps targets inside acquisition and expanded boundaries", async () => { const profile = await defaultTargetingProfile(); for (const target of [candidate("current", 0, 10), candidate("current", 70, 32)]) { const ctx = context([target], target.id); assert.equal(evaluateCandidate(profile, ctx, target, "retention").eligible, true); } });
test("brief invalidity clears grace without lock loss", async () => { const profile = await defaultTargetingProfile(); const invalid = { ...candidate("current", 0, 10), lineOfSight: false }; const valid = candidate("current", 0, 10); const result = runRetentionSequence(profile, [context([invalid], "current"), context([valid], "current")]); assert.equal(result.finalTargetId, "current"); assert.equal(result.graceCleared, true); assert.equal(result.releaseTimeSeconds, null); });
test("grace expiry releases at the exact fixed step and zero grace releases first step", async () => { const profile = await defaultTargetingProfile(); const invalid = { ...candidate("current", 0, 10), lineOfSight: false }; const steps = Math.ceil(profile.retention.lostTargetGraceSeconds / TARGETING_FIXED_DELTA_SECONDS); const contexts = Array.from({ length: steps }, () => context([invalid], "current")); const result = runRetentionSequence({ ...profile, retention: { ...profile.retention, autoReacquire: false } }, contexts); assert.equal(result.releaseTimeSeconds, steps * TARGETING_FIXED_DELTA_SECONDS); const zero = runRetentionSequence({ ...profile, retention: { ...profile.retention, lostTargetGraceSeconds: 0, autoReacquire: false } }, [context([invalid], "current")]); assert.equal(zero.releaseTimeSeconds, TARGETING_FIXED_DELTA_SECONDS); });
test("automatic reacquisition respects enablement and missing alternatives", async () => { const profile = await defaultTargetingProfile(); const invalid = { ...candidate("current", 0, 10), lineOfSight: false }; const replacement = candidate("replacement", 0, 8); const sequence = Array.from({ length: 30 }, () => context([invalid, replacement], "current")); assert.equal(runRetentionSequence(profile, sequence).finalTargetId, "replacement"); assert.equal(runRetentionSequence({ ...profile, retention: { ...profile.retention, autoReacquire: false } }, sequence).finalTargetId, null); const none = Array.from({ length: 30 }, () => context([invalid], "current")); assert.equal(runRetentionSequence(profile, none).finalTargetId, null); });
test("switching chooses left/right and handles wraparound", async () => { const profile = await defaultTargetingProfile(); const current = candidate("current", 179, 10); const wrappedLeft = candidate("left", -170, 10); const wrappedRight = candidate("right", 170, 10); const ctx = context([current, wrappedLeft, wrappedRight], current.id); ctx.viewForward = { x: current.targetPoint.x / 10, y: 0, z: current.targetPoint.z / 10 }; assert.equal(switchTarget(profile, ctx, "left").targetId, "left"); assert.equal(switchTarget(profile, ctx, "right").targetId, "right"); });
test("switching exclusions and structured unchanged reasons are stable", async () => { const profile = await defaultTargetingProfile(); const current = candidate("current", 0, 10); const tooClose = candidate("close", 1, 10); const tooFar = candidate("far", 130, 10); assert.equal(switchTarget(profile, context([current, tooClose, tooFar], current.id), "left").reason, "no_directional_candidate"); assert.equal(switchTarget(profile, context([current], null), "left").reason, "no_current_target"); assert.equal(switchTarget({ ...profile, switching: { ...profile.switching, enabled: false } }, context([current], current.id), "left").reason, "switching_disabled"); assert.equal(switchTarget(profile, context([current, candidate("left", 20, 10)], current.id), "left", 0.1).reason, "cooldown_active"); });
test("switch tie-breaking uses score, distance, then ordinal ID", async () => { const profile = await defaultTargetingProfile(); const current = candidate("current", 0, 10); const low = candidate("low", 20, 10, 0); const high = candidate("high", 20, 10, 1); assert.equal(switchTarget(profile, context([current, low, high], current.id), "left").targetId, "high"); const alpha = candidate("alpha", 20, 10, 0.5); const zeta = candidate("zeta", 20, 10, 0.5); assert.equal(switchTarget(profile, context([current, zeta, alpha], current.id), "left").targetId, "alpha"); });
test("all nine simulations are deterministic with structured timing and evidence", async () => { const profile = await defaultTargetingProfile(); for (const scenario of ["acquire", "eligibility", "tie-break", "retention", "loss", "reacquire", "switch-left", "switch-right", "switch-cooldown"] as const) { const first = simulateTargeting(profile, scenario); const second = simulateTargeting(profile, scenario); assert.deepEqual(first, second, scenario); assert.equal(typeof first.metrics.physicsSteps, "number"); assert.equal(first.metrics.fixedDeltaSeconds, 0.016666667); } });
test("switch-cooldown simulation rejects while active then succeeds", async () => { const metrics = simulateTargeting(await defaultTargetingProfile(), "switch-cooldown").metrics; assert.equal(metrics.initialCooldownRejected, true); assert.equal(metrics.switchingOccurred, true); assert.equal(metrics.finalTargetId, "left"); });
