import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { executeCli } from "../src/cli/main";
import type { OperationResult } from "../src/shared/operationResult";
import { ErrorCodes } from "../src/shared/errorCodes";
import { createTargetingTestWorkspace } from "./testUtils";

function runCli(root: string, args: string[]) { return spawnSync(process.execPath, [path.resolve(__dirname, "../src/cli/main.js"), ...args], { cwd: root, encoding: "utf8" }); }
test("targeting inspect and validate return structured read-only results", async (context) => { const workspace = await createTargetingTestWorkspace(context); for (const action of ["inspect", "validate"]) { const process = runCli(workspace.root, ["targeting", action, workspace.relativeFile, "--json"]); assert.equal(process.status, 0, process.stderr); const result = JSON.parse(process.stdout) as OperationResult; assert.equal(result.command, `targeting.${action}`); assert.equal(result.status, "passed"); assert.deepEqual(result.changedFiles, []); } });
test("targeting inspection reports derived retention, scoring, LOS, reacquisition, and switching data", async (context) => { const workspace = await createTargetingTestWorkspace(context); const result = (await executeCli(["targeting", "inspect", workspace.relativeFile, "--json"], workspace.root)).result; const metrics = (result.data as any).derivedMetrics; assert.equal(metrics.scoringWeightSum, 1); assert.equal(metrics.retentionMaximumDistance, 36); assert.equal(metrics.retentionMaximumAngleDegrees, 75); assert.equal(metrics.lineOfSightRequired, true); assert.equal(metrics.automaticReacquisitionEnabled, true); assert.equal(metrics.switchingAngularRangeDegrees, 120); assert.equal(metrics.switchingCooldownSeconds, 0.2); });
test("targeting CLI executes every deterministic simulation scenario read-only", async (context) => { const workspace = await createTargetingTestWorkspace(context); for (const scenario of ["acquire", "eligibility", "tie-break", "retention", "loss", "reacquire", "switch-left", "switch-right", "switch-cooldown"]) { const execution = await executeCli(["targeting", "simulate", workspace.relativeFile, "--scenario", scenario, "--json"], workspace.root); assert.equal(execution.result.status, "passed", scenario); assert.deepEqual(execution.result.changedFiles, []); assert.equal((execution.result.data as any).scenario, scenario); } });
test("unsupported targeting scenario uses stable code", async () => { const execution = await executeCli(["targeting", "simulate", "examples/targeting/default.json", "--scenario", "lock-camera", "--json"]); assert.equal(execution.exitCode, 2); assert.equal(execution.result.errors[0]?.code, ErrorCodes.TargetingScenarioUnsupported); });
test("targeting set dry-run parses JSON and remains read-only", async (context) => { const workspace = await createTargetingTestWorkspace(context); const process = runCli(workspace.root, ["targeting", "set", workspace.relativeFile, "acquisition.maximumDistance", "35", "--dry-run", "--json"]); assert.equal(process.status, 0, process.stderr); const result = JSON.parse(process.stdout) as OperationResult; assert.equal(result.status, "dry_run"); assert.deepEqual(result.changedFiles, []); });
test("targeting normal failures do not expose stack traces", async (context) => { const workspace = await createTargetingTestWorkspace(context); const process = runCli(workspace.root, ["targeting", "set", workspace.relativeFile, "missing", "1", "--json"]); assert.notEqual(process.status, 0); assert.equal(process.stderr.includes("Error:"), false); assert.equal(process.stderr.includes(" at "), false); });
test("targeting missing and malformed files use stable errors", async (context) => { const workspace = await createTargetingTestWorkspace(context); const missing = await executeCli(["targeting", "validate", "examples/targeting/missing.json", "--json"], workspace.root); assert.equal(missing.result.errors[0]?.code, ErrorCodes.TargetingFileNotFound); await writeFile(workspace.targetingFile, "{bad", "utf8"); const malformed = await executeCli(["targeting", "validate", workspace.relativeFile, "--json"], workspace.root); assert.equal(malformed.result.errors[0]?.code, ErrorCodes.TargetingJsonInvalid); });
