import assert from "node:assert/strict";
import test from "node:test";

import { compareTargetingRuntime } from "../src/application/runtime/compareTargetingRuntime";
import { buildTargetingRuntimePlan } from "../src/domain/runtime/targetingRuntimePlan";
import { simulateTargetingRuntime } from "../src/domain/runtime/targetingRuntimeSimulation";
import { defaultCameraProfile, defaultTargetingProfile } from "./testUtils";

async function values() { const targeting = await defaultTargetingProfile(); const simulation = simulateTargetingRuntime(targeting, await defaultCameraProfile(), buildTargetingRuntimePlan(targeting, "acquire")); return { simulation, runtime: structuredClone(simulation.metrics) as Record<string, any> }; }
test("targeting comparison accepts candidate order differences and score tolerance", async () => { const item = await values(); item.runtime.candidateEvaluations.reverse(); item.runtime.candidateEvaluations[0].totalScore += 0.0000005; assert.equal(compareTargetingRuntime(item.simulation, item.runtime).passed, true); });
test("targeting comparison rejects ID, code, boolean, and exact-step mismatches", async () => { for (const mutate of [(r: any) => r.finalTargetId = "wrong", (r: any) => r.candidateEvaluations[0].rejectionCodes = ["WRONG"], (r: any) => r.framingActive = false, (r: any) => r.physicsSteps += 1]) { const item = await values(); mutate(item.runtime); assert.equal(compareTargetingRuntime(item.simulation, item.runtime).passed, false); } });
test("targeting comparison applies camera and lens tolerances", async () => { const item = await values(); item.runtime.finalCameraYawDegrees += 0.2; item.runtime.finalCameraPosition.x += 0.04; item.runtime.lens.fieldOfViewDegrees += 0.0005; assert.equal(compareTargetingRuntime(item.simulation, item.runtime).passed, true); item.runtime.finalCameraYawDegrees += 0.1; assert.equal(compareTargetingRuntime(item.simulation, item.runtime).passed, false); });
test("targeting comparison rejects missing and non-finite metrics", async () => { const missing = await values(); delete missing.runtime.lockState; assert.equal(compareTargetingRuntime(missing.simulation, missing.runtime).passed, false); const nonfinite = await values(); nonfinite.runtime.finalCameraYawDegrees = Number.NaN; assert.equal(compareTargetingRuntime(nonfinite.simulation, nonfinite.runtime).passed, false); });
test("targeting comparison rejects score, angle, framing, lens, and switch reason outside tolerance", async () => { const mutations = [(r: any) => r.candidateEvaluations[0].totalScore += 0.000002, (r: any) => r.candidateEvaluations[0].unsignedAngleDegrees += 0.3, (r: any) => r.finalCameraPosition.x += 0.06, (r: any) => r.finalFramingAngularErrorDegrees += 0.3, (r: any) => r.lens.nearClipDistance += 0.002]; for (const mutate of mutations) { const item = await values(); mutate(item.runtime); assert.equal(compareTargetingRuntime(item.simulation, item.runtime).passed, false); } const targeting = await defaultTargetingProfile(); const simulation = simulateTargetingRuntime(targeting, await defaultCameraProfile(), buildTargetingRuntimePlan(targeting, "switch-cooldown")); const runtime = structuredClone(simulation.metrics) as any; runtime.switchRequests[0].reason = "no_directional_candidate"; assert.equal(compareTargetingRuntime(simulation, runtime).passed, false); });
test("targeting comparison accepts a time difference of one fixed step", async () => { const targeting = await defaultTargetingProfile(); const simulation = simulateTargetingRuntime(targeting, await defaultCameraProfile(), buildTargetingRuntimePlan(targeting, "loss")); const runtime = structuredClone(simulation.metrics) as any; runtime.releaseTimeSeconds += 1 / 60; assert.equal(compareTargetingRuntime(simulation, runtime).passed, true); });
