import assert from "node:assert/strict";
import test from "node:test";

import { buildTargetingRuntimePlan } from "../src/domain/runtime/targetingRuntimePlan";
import { RUNTIME_RUN_COMMAND, RUNTIME_SCHEMA_VERSION, TARGETING_FIXTURE_ID, type TargetingRuntimeRequest } from "../src/domain/runtime/runtimeProtocol";
import { validateRuntimeRequest } from "../src/domain/runtime/runtimeValidation";
import { defaultCameraProfile, defaultTargetingProfile } from "./testUtils";

async function request(): Promise<TargetingRuntimeRequest> { const profile = await defaultTargetingProfile(); return { schemaVersion: RUNTIME_SCHEMA_VERSION, commandId: RUNTIME_RUN_COMMAND, fixtureId: TARGETING_FIXTURE_ID, correlationId: "targeting-1", requestedAt: new Date(0).toISOString(), timeoutMs: 15000, payload: { definitionKind: "targeting-profile", definitionSchemaVersion: 1, profile, cameraDefinitionKind: "camera-profile", cameraDefinitionSchemaVersion: 1, cameraProfile: await defaultCameraProfile(), scenario: buildTargetingRuntimePlan(profile, "acquire") } }; }

test("valid targeting runtime request contains profiles and an ephemeral plan", async () => assert.equal(validateRuntimeRequest(await request()).valid, true));
test("targeting fixture discriminant carries complete profiles and no canonical paths", async () => { const value = await request(); assert.equal(value.fixtureId, TARGETING_FIXTURE_ID); assert.equal(value.payload.profile.kind, "targeting-profile"); assert.equal(value.payload.cameraProfile.kind, "camera-profile"); const serialized = JSON.stringify(value); assert.equal(serialized.includes("examples/targeting"), false); assert.equal(serialized.includes("examples/camera"), false); });
test("targeting runtime request rejects an unsupported fixture and scenario", async () => { const fixture: any = await request(); fixture.fixtureId = "targeting/other"; assert.equal(validateRuntimeRequest(fixture).valid, false); const scenario: any = await request(); scenario.payload.scenario.id = "orbit"; assert.equal(validateRuntimeRequest(scenario).valid, false); });
test("targeting runtime request rejects either wrong definition kind", async () => { const targeting: any = await request(); targeting.payload.definitionKind = "camera-profile"; assert.equal(validateRuntimeRequest(targeting).valid, false); const camera: any = await request(); camera.payload.cameraDefinitionKind = "targeting-profile"; assert.equal(validateRuntimeRequest(camera).valid, false); });
test("targeting runtime request rejects unsupported profile versions", async () => { const value: any = await request(); value.payload.definitionSchemaVersion = 2; value.payload.cameraDefinitionSchemaVersion = 2; assert.match(validateRuntimeRequest(value).errors.join(" "), /schema version/); });
test("targeting runtime plan rejects duplicate IDs and bad event targets", async () => { const value: any = await request(); value.payload.scenario.candidates[1].id = value.payload.scenario.candidates[0].id; value.payload.scenario.events.push({ step: 1, type: "set-targetable", targetId: "missing", targetable: false }); const errors = validateRuntimeRequest(value).errors.join(" "); assert.match(errors, /duplicate candidate ID/); assert.match(errors, /target ID invalid/); });
test("targeting runtime plan rejects non-finite values and contradictory events", async () => { const value: any = await request(); value.payload.scenario.candidates[0].priority = Number.NaN; value.payload.scenario.events.push({ step: 1, type: "request-acquire" }); const errors = validateRuntimeRequest(value).errors.join(" "); assert.match(errors, /priority invalid/); assert.match(errors, /duplicate or contradictory event/); });
test("targeting runtime plan rejects bad fixed delta, event steps, payloads, and target directions", async () => { const delta: any = await request(); delta.payload.scenario.fixedDeltaSeconds = 0; assert.match(validateRuntimeRequest(delta).errors.join(" "), /fixedDeltaSeconds/); const value: any = await request(); value.payload.scenario.events[0].extra = true; value.payload.scenario.events.push({ step: 99, type: "request-acquire" }); value.payload.scenario.candidates[0].targetPoint = value.payload.scenario.origin; const errors = validateRuntimeRequest(value).errors.join(" "); assert.match(errors, /step invalid/); assert.match(errors, /unsupported fields/); assert.match(errors, /direction undefined/); });
