import assert from "node:assert/strict";
import test from "node:test";

import { buildTargetingRuntimePlan, validateTargetingRuntimePlan, type TargetingRuntimeScenario } from "../src/domain/runtime/targetingRuntimePlan";
import { defaultTargetingProfile } from "./testUtils";

const scenarios: TargetingRuntimeScenario[] = ["acquire", "eligibility", "tie-break", "retention", "loss", "reacquire", "switch-left", "switch-right", "switch-cooldown", "framing-acquire", "framing-switch", "framing-loss", "framing-reacquire"];
test("all targeting runtime plans are deterministic and valid", async () => { const profile = await defaultTargetingProfile(); for (const scenario of scenarios) { const first = buildTargetingRuntimePlan(profile, scenario); assert.deepEqual(first, buildTargetingRuntimePlan(profile, scenario)); assert.deepEqual(validateTargetingRuntimePlan(first), [], scenario); } });
test("plans own exact acquisition, eligibility, tie, retention, loss, switch, cooldown, and framing geometry", async () => { const profile = await defaultTargetingProfile(); assert.equal(buildTargetingRuntimePlan(profile, "acquire").events[0]?.step, 1); assert.equal(buildTargetingRuntimePlan(profile, "eligibility").candidates.length, 6); assert.deepEqual(buildTargetingRuntimePlan(profile, "tie-break").candidates.map((item) => item.id), ["zeta", "alpha"]); assert.notEqual(buildTargetingRuntimePlan(profile, "retention").initialTargetId, null); assert.equal(buildTargetingRuntimePlan(profile, "loss").events[0]?.type, "set-obstruction"); assert.equal(buildTargetingRuntimePlan(profile, "reacquire").candidates.length, 2); assert.equal(buildTargetingRuntimePlan(profile, "switch-left").events[0]?.type, "request-switch"); assert(buildTargetingRuntimePlan(profile, "switch-cooldown").events.length === 2); assert(buildTargetingRuntimePlan(profile, "framing-switch").events[0]?.step === 30); });
test("plan validation rejects malformed candidates, IDs, events, steps, delta, scenario, cooldown, and non-finite values", async () => { const profile = await defaultTargetingProfile(); const mutations: Array<(plan: any) => void> = [(p) => { p.id = "bad"; }, (p) => { p.fixedDeltaSeconds = 0; }, (p) => { p.origin.x = Number.NaN; }, (p) => { p.viewForward = { x: 0, y: 0, z: 0 }; }, (p) => { p.initialSwitchCooldownSeconds = -1; }, (p) => { p.candidates[1].id = p.candidates[0].id; }, (p) => { p.candidates[0].priority = 2; }, (p) => { p.initialTargetId = "missing"; }, (p) => { p.events[0].step = 999; }, (p) => { p.events[0] = { step: 1, type: "set-targetable", targetId: "missing", targetable: true }; }, (p) => { p.events.push(structuredClone(p.events[0])); }]; for (const mutate of mutations) { const plan: any = buildTargetingRuntimePlan(profile, "acquire"); mutate(plan); assert(validateTargetingRuntimePlan(plan).length > 0); } });
test("origin-overlap eligibility candidate is valid scenario data", async () => { const plan = buildTargetingRuntimePlan(await defaultTargetingProfile(), "eligibility"); assert.equal(validateTargetingRuntimePlan(plan).length, 0); assert(plan.candidates.some((item) => item.id === "overlap" && item.targetPoint.x === 0 && item.targetPoint.z === 0)); });
