import type { DamageReactionProfile } from "../../domain/damageReaction/damageReactionTypes";
import { validateDamageReactionDefinition } from "../../domain/damageReaction/damageReactionValidation";
import { resolveWorkspacePath } from "../../infrastructure/files/changedFileAudit";
import { JsonFileReadError, readJsonFile } from "../../infrastructure/files/jsonFileStore";
import { ErrorCodes } from "../../shared/errorCodes";
import type { OperationError } from "../../shared/operationResult";

export interface LoadedDamageReaction { absolutePath: string; relativePath: string; content: string; profile: DamageReactionProfile }
export interface LoadDamageReactionFailure { errors: OperationError[]; absolutePath?: string; relativePath?: string }
export async function loadValidDamageReaction(workspaceRoot: string, inputFile: string): Promise<LoadedDamageReaction | LoadDamageReactionFailure> { let resolved: { absolutePath: string; relativePath: string }; try { resolved = resolveWorkspacePath(workspaceRoot, inputFile); } catch (caught) { return { errors: [{ code: ErrorCodes.DamageReactionWriteBlocked, path: inputFile, message: caught instanceof Error ? caught.message : String(caught) }] }; } let read: Awaited<ReturnType<typeof readJsonFile>>; try { read = await readJsonFile(resolved.absolutePath); } catch (caught) { if (caught instanceof JsonFileReadError) { const code = caught.kind === "not_found" ? ErrorCodes.DamageReactionFileNotFound : caught.kind === "invalid_json" ? ErrorCodes.DamageReactionJsonInvalid : ErrorCodes.DamageReactionFileReadFailed; return { ...resolved, errors: [{ code, path: resolved.relativePath, message: `Damage reaction file ${caught.kind === "not_found" ? "was not found" : caught.kind === "invalid_json" ? "contains invalid JSON" : "could not be read"}` }] }; } throw caught; } const validation = validateDamageReactionDefinition(read.value); return validation.valid && validation.profile ? { ...resolved, content: read.content, profile: validation.profile } : { ...resolved, errors: validation.errors }; }
export function isLoadedDamageReaction(value: LoadedDamageReaction | LoadDamageReactionFailure): value is LoadedDamageReaction { return "profile" in value; }
