import { simulateDamageReactionHit } from "../../domain/damageReaction/damageReactionSimulation";
import { auditChangedFiles, captureWorkspaceState } from "../../infrastructure/files/changedFileAudit";
import { ErrorCodes } from "../../shared/errorCodes";
import { operationResult, type OperationResult } from "../../shared/operationResult";
import { isLoadedHealth, loadValidHealth } from "../health/healthOperationSupport";
import { isLoadedOffensiveAction, loadValidOffensiveAction } from "../offensiveAction/offensiveActionOperationSupport";
import { isLoadedDamageReaction, loadValidDamageReaction } from "./damageReactionOperationSupport";

export async function simulateDamageReactionFiles(workspaceRoot: string, reactionFile: string, healthFile: string, offensiveActionFile: string, targetActionWasActive = false): Promise<OperationResult> { const command = "damage-reaction.simulate-hit"; const input = { reactionFile, healthFile, offensiveActionFile, targetActionWasActive }; const before = await captureWorkspaceState(workspaceRoot); const reaction = await loadValidDamageReaction(workspaceRoot, reactionFile); if (!isLoadedDamageReaction(reaction)) return operationResult({ command, status: "failed", input, errors: reaction.errors }); const health = await loadValidHealth(workspaceRoot, healthFile); if (!isLoadedHealth(health)) return operationResult({ command, status: "failed", input: { ...input, reactionFile: reaction.relativePath }, errors: health.errors }); const action = await loadValidOffensiveAction(workspaceRoot, offensiveActionFile); if (!isLoadedOffensiveAction(action)) return operationResult({ command, status: "failed", input: { ...input, reactionFile: reaction.relativePath, healthFile: health.relativePath }, errors: action.errors }); const simulation = simulateDamageReactionHit(reaction.profile, health.profile, action.profile, targetActionWasActive); const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); if (!audit.ok) return operationResult({ command, status: "failed", input, errors: [{ code: ErrorCodes.DamageReactionWriteBlocked, message: "Read-only damage reaction simulation changed unexpected files", details: { unexpectedFiles: audit.unexpectedFiles } }], changedFiles: audit.changedFiles }); return operationResult({ command, status: "passed", input: { reactionFile: reaction.relativePath, healthFile: health.relativePath, offensiveActionFile: action.relativePath, targetActionWasActive }, data: simulation }); }
