import { validateOffensiveActionDefinition } from "../../domain/offensiveAction/offensiveActionValidation";
import type { OffensiveActionProfile } from "../../domain/offensiveAction/offensiveActionTypes";
import { auditChangedFiles, captureWorkspaceState, resolveWorkspacePath } from "../../infrastructure/files/changedFileAudit";
import { formatJson } from "../../infrastructure/files/jsonFileStore";
import { createFileSnapshot, type CreatedSnapshot } from "../../infrastructure/snapshots/fileSnapshotStore";
import { ErrorCodes } from "../../shared/errorCodes";
import { operationResult, type OperationError, type OperationResult } from "../../shared/operationResult";
import { transactionalFileReplace, type ContentVerification, type TransactionalFileReplaceDependencies, type TransactionalReplaceFailure } from "../persistence/transactionalFileReplace";
import { withTargetOperationLock } from "../persistence/targetOperationLock";
import { isLoadedOffensiveAction, loadValidOffensiveAction } from "./offensiveActionOperationSupport";

export interface SetOffensiveActionValueDependencies { createSnapshot: typeof createFileSnapshot; transaction: Partial<TransactionalFileReplaceDependencies>; verifyContent: (content: string) => ContentVerification<OffensiveActionProfile> }
const productionDependencies: SetOffensiveActionValueDependencies = { createSnapshot: createFileSnapshot, transaction: {}, verifyContent: verifyOffensiveActionContent };
export async function setOffensiveActionValue(workspaceRoot: string, inputFile: string, propertyPath: string, value: unknown, dryRun: boolean, injected: Partial<SetOffensiveActionValueDependencies> = {}): Promise<OperationResult> { const dependencies = { ...productionDependencies, ...injected, transaction: { ...productionDependencies.transaction, ...injected.transaction } }; if (dryRun) return executeSet(workspaceRoot, inputFile, propertyPath, value, true, dependencies); let relativePath: string; try { relativePath = resolveWorkspacePath(workspaceRoot, inputFile).relativePath; } catch (caught) { return operationResult({ command: "offensive-action.set", status: "failed", input: { file: inputFile, propertyPath, value, dryRun }, errors: [{ code: ErrorCodes.OffensiveActionWriteBlocked, path: inputFile, message: caught instanceof Error ? caught.message : String(caught) }] }); } return withTargetOperationLock(workspaceRoot, relativePath, () => executeSet(workspaceRoot, inputFile, propertyPath, value, false, dependencies)); }
async function executeSet(workspaceRoot: string, inputFile: string, propertyPath: string, value: unknown, dryRun: boolean, dependencies: SetOffensiveActionValueDependencies): Promise<OperationResult> { const command = "offensive-action.set"; const input = { file: inputFile, propertyPath, value, dryRun }; const before = await captureWorkspaceState(workspaceRoot); const loaded = await loadValidOffensiveAction(workspaceRoot, inputFile); if (!isLoadedOffensiveAction(loaded)) return operationResult({ command, status: "failed", input, errors: loaded.errors }); const candidate = structuredClone(loaded.profile) as OffensiveActionProfile; if (!Object.prototype.hasOwnProperty.call(candidate, propertyPath) || ["__proto__", "prototype", "constructor"].includes(propertyPath)) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: [{ code: ErrorCodes.OffensiveActionPropertyNotFound, path: propertyPath, message: "Only existing schema-defined offensive action properties may be edited" }] }); (candidate as unknown as Record<string, unknown>)[propertyPath] = value; const validation = validateOffensiveActionDefinition(candidate); if (!validation.valid || !validation.profile) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: validation.errors.map((error) => error.code === ErrorCodes.OffensiveActionSchemaInvalid ? { ...error, code: ErrorCodes.OffensiveActionPropertyValueInvalid } : error) }); if (dryRun) { const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); if (!audit.ok) return operationResult({ command, status: "failed", input, errors: [{ code: ErrorCodes.OffensiveActionWriteScopeAuditFailed, message: "Offensive action dry run changed files outside its zero-write scope", details: { unexpectedFiles: audit.unexpectedFiles } }], changedFiles: audit.changedFiles }); return operationResult({ command, status: "dry_run", input: { ...input, file: loaded.relativePath }, data: { profile: validation.profile, proposedChange: { path: propertyPath, value } } }); }
  let snapshot: CreatedSnapshot; try { snapshot = await dependencies.createSnapshot(workspaceRoot, loaded.relativePath, loaded.content, command, "offensive-action-profile"); } catch (caught) { const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: [{ code: ErrorCodes.OffensiveActionWriteBlocked, path: loaded.relativePath, message: `Pre-write snapshot could not be created: ${caught instanceof Error ? caught.message : String(caught)}` }], changedFiles: audit.changedFiles }); }
  const transaction = await transactionalFileReplace({ workspaceRoot, operationStartState: before, targetAbsolutePath: loaded.absolutePath, targetRelativePath: loaded.relativePath, replacementContent: formatJson(validation.profile), originalContent: loaded.content, allowedPaths: [loaded.relativePath, snapshot.relativePath], verifyContent: dependencies.verifyContent, dependencies: dependencies.transaction }); if (!transaction.ok) return transactionFailure(command, { ...input, file: loaded.relativePath }, transaction, snapshot.record.snapshotId); return operationResult({ command, status: "passed", input: { ...input, file: loaded.relativePath }, data: { profile: transaction.value, appliedChange: { path: propertyPath, value } }, changedFiles: transaction.changedFiles, snapshotId: snapshot.record.snapshotId }); }
export function verifyOffensiveActionContent(content: string): ContentVerification<OffensiveActionProfile> { let value: unknown; try { value = JSON.parse(content) as unknown; } catch { return { validationPassed: false, errors: [{ code: ErrorCodes.OffensiveActionJsonInvalid, message: "Persisted offensive action content is not valid JSON" }] }; } const validation = validateOffensiveActionDefinition(value); return validation.valid && validation.profile ? { validationPassed: true, value: validation.profile } : { validationPassed: false, errors: validation.errors }; }
function transactionFailure(command: string, input: Record<string, unknown>, transaction: TransactionalReplaceFailure, snapshotId: string): OperationResult { const errors: OperationError[] = [{ code: transaction.failureStage === "scope_audit" ? ErrorCodes.OffensiveActionWriteScopeAuditFailed : ErrorCodes.OffensiveActionWriteVerificationFailed, message: transaction.failureMessage, details: { failureStage: transaction.failureStage, unexpectedFiles: transaction.unexpectedFiles, verificationErrors: transaction.verificationErrors } }]; if (transaction.recovery.status === "failed") errors.push({ code: ErrorCodes.OffensiveActionWriteRecoveryFailed, path: transaction.recovery.restoredFile, message: "Offensive action write recovery could not verify the exact original target state", details: { recovery: transaction.recovery } }); return operationResult({ command, status: "failed", input, data: { failureStage: transaction.failureStage, recovery: transaction.recovery }, errors, changedFiles: transaction.changedFiles, snapshotId }); }
