import type { TargetingProfile, TargetingVector3 } from "../targeting/targetingTypes";

export type TargetingRuntimeScenario = "acquire" | "eligibility" | "tie-break" | "retention" | "loss" | "reacquire" | "switch-left" | "switch-right" | "switch-cooldown" | "framing-acquire" | "framing-switch" | "framing-loss" | "framing-reacquire";
export interface TargetingRuntimeCandidate { id: string; targetPoint: TargetingVector3; targetable: boolean; priority: number; obstruction: "none" | "controlled-wall" }
export type TargetingRuntimeEvent = { step: number; type: "request-acquire" } | { step: number; type: "set-obstruction"; targetId: string; obstruction: "none" | "controlled-wall" } | { step: number; type: "set-targetable"; targetId: string; targetable: boolean } | { step: number; type: "move-target"; targetId: string; targetPoint: TargetingVector3 } | { step: number; type: "request-switch"; direction: "left" | "right" };
export interface TargetingRuntimeScenarioRequest { id: TargetingRuntimeScenario; durationSeconds: number; fixedDeltaSeconds: number; origin: TargetingVector3; viewForward: TargetingVector3; initialTargetId: string | null; initialSwitchCooldownSeconds: number; candidates: TargetingRuntimeCandidate[]; events: TargetingRuntimeEvent[] }
export const TARGETING_RUNTIME_SCENARIOS = new Set<TargetingRuntimeScenario>(["acquire", "eligibility", "tie-break", "retention", "loss", "reacquire", "switch-left", "switch-right", "switch-cooldown", "framing-acquire", "framing-switch", "framing-loss", "framing-reacquire"]);
const EPSILON = 1e-12;

export function buildTargetingRuntimePlan(profile: TargetingProfile, scenario: TargetingRuntimeScenario, seconds?: number, fixedDelta = 1 / 60): TargetingRuntimeScenarioRequest {
  const duration = seconds ?? defaultDuration(profile, scenario, fixedDelta); const steps = stepCount(duration, fixedDelta); const acquire = { step: 1, type: "request-acquire" } as const;
  const common = { id: scenario, durationSeconds: steps * fixedDelta, fixedDeltaSeconds: fixedDelta, origin: vector(0, 0, 0), viewForward: vector(0, 0, -1), initialTargetId: null, initialSwitchCooldownSeconds: 0 };
  if (scenario === "eligibility") return { ...common, candidates: [candidate("visible", 0, 10, 0.5), candidate("too-far", 0, profile.acquisition.maximumDistance + 2, 0.5), candidate("too-wide", profile.acquisition.maximumAngleDegrees + 10, 10, 0.5), candidate("blocked", 25, 14, 0.5, "controlled-wall"), { ...candidate("untargetable", 0, 12, 0.5), targetable: false }, { ...candidate("overlap", 0, 1, 0.5), targetPoint: vector(0, 0, 0) }], events: [acquire] };
  if (scenario === "tie-break") return { ...common, candidates: [candidate("zeta", 10, 12, 0.5), candidate("alpha", 10, 12, 0.5)], events: [acquire] };
  if (scenario === "retention") { const current = candidate("current", profile.acquisition.maximumAngleDegrees + profile.retention.additionalAngleDegrees / 2, profile.acquisition.maximumDistance * Math.min(1.1, profile.retention.maximumDistanceMultiplier), 0.5); return { ...common, initialTargetId: current.id, candidates: [current], events: [] }; }
  if (["loss", "reacquire", "framing-loss", "framing-reacquire"].includes(scenario)) { const current = candidate("current", 0, 10, 0.5); const replacement = candidate("replacement", 25, 9, 0.8); const includeReplacement = scenario === "reacquire" || scenario === "framing-reacquire"; return { ...common, initialTargetId: current.id, candidates: includeReplacement ? [current, replacement] : [current], events: [{ step: 1, type: "set-obstruction", targetId: current.id, obstruction: "controlled-wall" }] }; }
  if (scenario === "switch-left" || scenario === "switch-right") { const currentYaw = scenario === "switch-left" ? 179 : -179; const current = candidate("current", currentYaw, 10, 0.5); const selected = candidate(scenario === "switch-left" ? "left-wrap" : "right-wrap", scenario === "switch-left" ? -170 : 170, 10, 0.7); const forward = direction(currentYaw); return { ...common, viewForward: forward, initialTargetId: current.id, candidates: [current, selected], events: [{ step: 1, type: "request-switch", direction: scenario === "switch-left" ? "left" : "right" }] }; }
  if (scenario === "switch-cooldown") { const current = candidate("current", 0, 10, 0.5); const availableStep = Math.ceil(profile.switching.cooldownSeconds / fixedDelta - EPSILON) + 1; return { ...common, initialTargetId: current.id, initialSwitchCooldownSeconds: profile.switching.cooldownSeconds, candidates: [current, candidate("left", 20, 10, 0.7)], events: [{ step: 1, type: "request-switch", direction: "left" }, { step: Math.min(steps, availableStep), type: "request-switch", direction: "left" }] }; }
  if (scenario === "framing-switch") { const current = candidate("current", -25, 10, 0.5); return { ...common, initialTargetId: current.id, candidates: [current, candidate("left", 30, 10, 0.8)], events: [{ step: Math.min(steps, 30), type: "request-switch", direction: "left" }] }; }
  const candidates = [candidate("near", 0, 10, 0.2), candidate("angled", 30, 12, 0.9), candidate("far", 0, 25, 1)]; return { ...common, candidates, events: [acquire] };
}

export function validateTargetingRuntimePlan(plan: unknown): string[] {
  const errors: string[] = []; if (!record(plan)) return ["scenario must be an object"];
  exactKeys(plan, ["id", "durationSeconds", "fixedDeltaSeconds", "origin", "viewForward", "initialTargetId", "initialSwitchCooldownSeconds", "candidates", "events"], "scenario", errors);
  if (!TARGETING_RUNTIME_SCENARIOS.has(plan.id as TargetingRuntimeScenario)) errors.push("unsupported targeting runtime scenario");
  if (!finite(plan.durationSeconds) || plan.durationSeconds <= 0 || plan.durationSeconds > 60) errors.push("invalid durationSeconds");
  if (!finite(plan.fixedDeltaSeconds) || plan.fixedDeltaSeconds <= 0 || plan.fixedDeltaSeconds > 1) errors.push("invalid fixedDeltaSeconds");
  validateVector(plan.origin, "origin", errors); validateVector(plan.viewForward, "viewForward", errors); if (record(plan.viewForward) && Math.hypot(Number(plan.viewForward.x), Number(plan.viewForward.y), Number(plan.viewForward.z)) <= EPSILON) errors.push("viewForward must be non-zero");
  if (!finite(plan.initialSwitchCooldownSeconds) || plan.initialSwitchCooldownSeconds < 0) errors.push("initialSwitchCooldownSeconds must be non-negative");
  if (!Array.isArray(plan.candidates)) errors.push("candidates must be an array"); const ids = new Set<string>();
  if (Array.isArray(plan.candidates)) plan.candidates.forEach((value, index) => { if (!record(value)) { errors.push(`candidate ${index} must be an object`); return; } exactKeys(value, ["id", "targetPoint", "targetable", "priority", "obstruction"], `candidate ${index}`, errors); if (typeof value.id !== "string" || value.id.length === 0) errors.push(`candidate ${index} id invalid`); else if (ids.has(value.id)) errors.push("duplicate candidate ID"); else ids.add(value.id); validateVector(value.targetPoint, `candidate ${index} targetPoint`, errors); if (sameVector(value.targetPoint, plan.origin) && !(plan.id === "eligibility" && value.id === "overlap")) errors.push(`candidate ${index} target direction undefined`); if (typeof value.targetable !== "boolean") errors.push(`candidate ${index} targetable invalid`); if (!finite(value.priority) || value.priority < 0 || value.priority > 1) errors.push(`candidate ${index} priority invalid`); if (!["none", "controlled-wall"].includes(String(value.obstruction))) errors.push(`candidate ${index} obstruction invalid`); });
  if (plan.initialTargetId !== null && (typeof plan.initialTargetId !== "string" || !ids.has(plan.initialTargetId))) errors.push("initialTargetId is invalid");
  const steps = finite(plan.durationSeconds) && finite(plan.fixedDeltaSeconds) && plan.fixedDeltaSeconds > 0 ? stepCount(plan.durationSeconds, plan.fixedDeltaSeconds) : 0; if (!Array.isArray(plan.events)) errors.push("events must be an array"); const keys = new Set<string>();
  if (Array.isArray(plan.events)) plan.events.forEach((event, index) => { if (!record(event) || !Number.isInteger(event.step) || event.step < 1 || event.step > steps) { errors.push(`event ${index} step invalid`); return; } const fields: Record<string, string[]> = { "request-acquire": ["step", "type"], "set-obstruction": ["step", "type", "targetId", "obstruction"], "set-targetable": ["step", "type", "targetId", "targetable"], "move-target": ["step", "type", "targetId", "targetPoint"], "request-switch": ["step", "type", "direction"] }; if (!fields[String(event.type)]) errors.push(`event ${index} type invalid`); else exactKeys(event, fields[String(event.type)] as string[], `event ${index}`, errors); const targetId = event.targetId; if (["set-obstruction", "set-targetable", "move-target"].includes(String(event.type)) && (typeof targetId !== "string" || !ids.has(targetId))) errors.push(`event ${index} target ID invalid`); if (event.type === "set-obstruction" && !["none", "controlled-wall"].includes(String(event.obstruction))) errors.push(`event ${index} obstruction invalid`); if (event.type === "set-targetable" && typeof event.targetable !== "boolean") errors.push(`event ${index} targetable invalid`); if (event.type === "move-target") { validateVector(event.targetPoint, `event ${index} targetPoint`, errors); if (sameVector(event.targetPoint, plan.origin)) errors.push(`event ${index} target direction undefined`); } if (event.type === "request-switch" && !["left", "right"].includes(String(event.direction))) errors.push(`event ${index} direction invalid`); const key = `${event.step}:${String(event.type)}:${String(targetId ?? "")}`; if (keys.has(key)) errors.push("duplicate or contradictory event"); keys.add(key); });
  return errors;
}

function defaultDuration(profile: TargetingProfile, scenario: TargetingRuntimeScenario, delta: number): number { if (["loss", "reacquire", "framing-loss", "framing-reacquire"].includes(scenario)) return profile.retention.lostTargetGraceSeconds + 1; if (scenario === "switch-cooldown") return profile.switching.cooldownSeconds + delta * 2; if (scenario.startsWith("framing-")) return 2; return delta; }
function stepCount(seconds: number, delta: number): number { return Math.max(1, Math.ceil(seconds / delta - EPSILON)); }
function candidate(id: string, yaw: number, distance: number, priority: number, obstruction: "none" | "controlled-wall" = "none"): TargetingRuntimeCandidate { const directionValue = direction(yaw); return { id, targetPoint: vector(directionValue.x * distance, 0, directionValue.z * distance), targetable: true, priority, obstruction }; }
function direction(yaw: number): TargetingVector3 { const radians = yaw * Math.PI / 180; return vector(-Math.sin(radians), 0, -Math.cos(radians)); }
function vector(x: number, y: number, z: number): TargetingVector3 { return { x, y, z }; }
function validateVector(value: unknown, path: string, errors: string[]): void { if (!record(value) || !finite(value.x) || !finite(value.y) || !finite(value.z)) errors.push(`${path} must contain finite components`); }
function finite(value: unknown): value is number { return typeof value === "number" && Number.isFinite(value); }
function record(value: unknown): value is Record<string, any> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function sameVector(left: unknown, right: unknown): boolean { return record(left) && record(right) && finite(left.x) && finite(left.y) && finite(left.z) && left.x === right.x && left.y === right.y && left.z === right.z; }
function exactKeys(value: Record<string, unknown>, allowed: string[], path: string, errors: string[]): void { const extra = Object.keys(value).filter((key) => !allowed.includes(key)); if (extra.length > 0) errors.push(`${path} contains unsupported fields`); }
