const REQUIRED = ["initialTargetId", "selectedTargetId", "finalTargetId", "targetIdHistory", "lockState", "tieBreakResult", "candidateEvaluations", "graceStartStep", "graceStartTimeSeconds", "graceExpiryStep", "graceExpiryTimeSeconds", "releaseStep", "releaseTimeSeconds", "reacquiredTargetId", "autoReacquire", "switchRequests", "framingActive", "framingActivePhysicsSteps", "framingTargetIdHistory", "initialCameraYawDegrees", "finalCameraYawDegrees", "initialCameraPitchDegrees", "finalCameraPitchDegrees", "initialFramingAngularErrorDegrees", "maximumFramingAngularErrorDegrees", "finalFramingAngularErrorDegrees", "finalCameraPosition", "finalFramingPoint", "finalSelectedTargetPoint", "cameraTranslationAfterRelease", "cameraAngularMovementAfterReleaseDegrees", "physicsSteps", "fixedDeltaSeconds", "lens"] as const;

export function validateTargetingRuntimeMetrics(metrics: Record<string, unknown>): string[] {
  const errors: string[] = []; for (const key of REQUIRED) if (!(key in metrics)) errors.push(`metrics.${key} is required`);
  for (const key of ["initialTargetId", "selectedTargetId", "finalTargetId", "tieBreakResult", "reacquiredTargetId"]) if (metrics[key] !== null && typeof metrics[key] !== "string") errors.push(`metrics.${key} must be a string or null`);
  for (const key of ["autoReacquire", "framingActive"]) if (typeof metrics[key] !== "boolean") errors.push(`metrics.${key} must be boolean`);
  for (const key of ["framingActivePhysicsSteps", "physicsSteps"]) if (!Number.isInteger(metrics[key]) || Number(metrics[key]) < 0) errors.push(`metrics.${key} must be a non-negative integer`);
  for (const key of ["initialCameraYawDegrees", "finalCameraYawDegrees", "initialCameraPitchDegrees", "finalCameraPitchDegrees", "maximumFramingAngularErrorDegrees", "cameraTranslationAfterRelease", "cameraAngularMovementAfterReleaseDegrees", "fixedDeltaSeconds"]) if (!finite(metrics[key])) errors.push(`metrics.${key} must be finite`);
  for (const key of ["targetIdHistory", "candidateEvaluations", "switchRequests", "framingTargetIdHistory"]) if (!Array.isArray(metrics[key])) errors.push(`metrics.${key} must be an array`);
  if (Array.isArray(metrics.candidateEvaluations)) metrics.candidateEvaluations.forEach((item, index) => { if (!record(item)) { errors.push(`metrics.candidateEvaluations.${index} must be an object`); return; } for (const key of ["id", "targetPoint", "targetable", "lineOfSight", "eligible", "rejectionCodes", "distance", "unsignedAngleDegrees", "signedHorizontalAngleDegrees", "distanceScore", "angleScore", "priorityScore", "totalScore"]) if (!(key in item)) errors.push(`metrics.candidateEvaluations.${index}.${key} is required`); if (typeof item.id !== "string" || typeof item.targetable !== "boolean" || typeof item.lineOfSight !== "boolean" || typeof item.eligible !== "boolean" || !Array.isArray(item.rejectionCodes) || !finite(item.distance) || !finite(item.priorityScore)) errors.push(`metrics.candidateEvaluations.${index} has invalid evidence`); vector(item.targetPoint, `metrics.candidateEvaluations.${index}.targetPoint`, errors); });
  vector(metrics.finalCameraPosition, "metrics.finalCameraPosition", errors); if (metrics.finalFramingPoint !== null) vector(metrics.finalFramingPoint, "metrics.finalFramingPoint", errors); if (metrics.finalSelectedTargetPoint !== null) vector(metrics.finalSelectedTargetPoint, "metrics.finalSelectedTargetPoint", errors);
  if (!record(metrics.lens) || !finite(metrics.lens.fieldOfViewDegrees) || !finite(metrics.lens.nearClipDistance) || !finite(metrics.lens.farClipDistance)) errors.push("metrics.lens must contain finite readback values");
  return errors;
}
function vector(value: unknown, path: string, errors: string[]): void { if (!record(value) || !finite(value.x) || !finite(value.y) || !finite(value.z)) errors.push(`${path} must contain finite components`); }
function finite(value: unknown): value is number { return typeof value === "number" && Number.isFinite(value); }
function record(value: unknown): value is Record<string, any> { return typeof value === "object" && value !== null && !Array.isArray(value); }
