import { halfLifeRemainingFraction, normalizeYawDegrees, shortestAngleDifferenceDegrees } from "../camera/cameraMath";
import type { CameraProfile } from "../camera/cameraTypes";
import { roundMetric } from "../movement/movementMetrics";
import { acquireTarget, evaluateCandidate, switchTarget, type TargetEvaluation } from "../targeting/targetingSimulation";
import type { TargetCandidate, TargetingContext, TargetingProfile, TargetingVector3 } from "../targeting/targetingTypes";
import type { TargetingRuntimeCandidate, TargetingRuntimeEvent, TargetingRuntimeScenarioRequest } from "./targetingRuntimePlan";

const EPSILON = 1e-12;
export interface TargetingRuntimeSimulation { scenario: TargetingRuntimeScenarioRequest["id"]; metrics: Record<string, unknown> }

export function simulateTargetingRuntime(profile: TargetingProfile, cameraProfile: CameraProfile, plan: TargetingRuntimeScenarioRequest): TargetingRuntimeSimulation {
  const candidates = new Map(plan.candidates.map((item) => [item.id, structuredClone(item)])); const steps = Math.max(1, Math.ceil(plan.durationSeconds / plan.fixedDeltaSeconds - EPSILON));
  let targetId = plan.initialTargetId; let selectedTargetId: string | null = targetId; let cooldown = plan.initialSwitchCooldownSeconds; let invalidElapsed = 0; let graceStartStep: number | null = null; let graceExpiryStep: number | null = null; let releaseStep: number | null = null; let reacquiredTargetId: string | null = null; let tieBreakResult: string | null = null;
  const targetHistory: Array<{ step: number; targetId: string | null }> = [{ step: 0, targetId }]; const switchRequests: Array<Record<string, unknown>> = [];
  let cameraYaw = cameraProfile.orbit.initialYawDegrees; let cameraPitch = cameraProfile.orbit.initialPitchDegrees; let cameraPosition = boomPosition(plan.origin, cameraYaw, cameraProfile); const initialCameraYaw = cameraYaw; const initialCameraPitch = cameraPitch; let framingSteps = 0; let initialFramingError: number | null = null; let maximumFramingError = 0; let finalFramingError: number | null = null; let lastFramingPoint: TargetingVector3 | null = null; let finalSelectedPoint: TargetingVector3 | null = null; const framingHistory: Array<{ step: number; targetId: string }> = []; let releaseCamera: { position: TargetingVector3; yaw: number; pitch: number } | null = null; let latestEvaluations: TargetEvaluation[] = [];
  const eventsByStep = new Map<number, TargetingRuntimeEvent[]>(); for (const event of plan.events) eventsByStep.set(event.step, [...(eventsByStep.get(event.step) ?? []), event]);
  for (let step = 1; step <= steps; step += 1) {
    const events = eventsByStep.get(step) ?? [];
    for (const event of events) { const item = "targetId" in event ? candidates.get(event.targetId) : undefined; if (event.type === "set-obstruction" && item) item.obstruction = event.obstruction; if (event.type === "set-targetable" && item) item.targetable = event.targetable; if (event.type === "move-target" && item) item.targetPoint = { ...event.targetPoint }; }
    cooldown = Math.max(0, cooldown - plan.fixedDeltaSeconds); const context = measuredContext(plan, candidates, targetId); latestEvaluations = runtimeEvaluations(profile, context);
    if (targetId !== null) { const current = context.candidates.find((item) => item.id === targetId); const valid = current ? evaluateCandidate(profile, context, current, "retention").eligible : false; if (valid) { invalidElapsed = 0; graceStartStep = null; } else { if (graceStartStep === null) graceStartStep = step; invalidElapsed += plan.fixedDeltaSeconds; if (profile.retention.lostTargetGraceSeconds === 0 || invalidElapsed + EPSILON >= profile.retention.lostTargetGraceSeconds) { graceExpiryStep = step; releaseStep = step; setTarget(null, step); if (profile.retention.autoReacquire) { const acquisition = acquireTarget(profile, { ...context, currentTargetId: null }); tieBreakResult = acquisition.tieBreakResult; reacquiredTargetId = acquisition.selectedTargetId; if (reacquiredTargetId !== null) setTarget(reacquiredTargetId, step); } releaseCamera = { position: { ...cameraPosition }, yaw: cameraYaw, pitch: cameraPitch }; } } }
    for (const event of events) if (event.type === "request-acquire" && targetId === null) { const acquisition = acquireTarget(profile, { ...measuredContext(plan, candidates, null), currentTargetId: null }); tieBreakResult = acquisition.tieBreakResult; selectedTargetId = acquisition.selectedTargetId; if (selectedTargetId !== null) setTarget(selectedTargetId, step); }
    for (const event of events) if (event.type === "request-switch") { const before = cooldown; const switched = switchTarget(profile, measuredContext(plan, candidates, targetId), event.direction, cooldown); if (switched.switched) { setTarget(switched.targetId, step); selectedTargetId = switched.targetId; cooldown = profile.switching.cooldownSeconds; } switchRequests.push({ direction: event.direction, requestStep: step, requestTimeSeconds: step * plan.fixedDeltaSeconds, switched: switched.switched, reason: switched.reason, cooldownBeforeSeconds: before, cooldownAfterSeconds: cooldown, successfulSwitchStep: switched.switched ? step : null, successfulSwitchTimeSeconds: switched.switched ? step * plan.fixedDeltaSeconds : null }); }
    if (targetId !== null) { const target = candidates.get(targetId); if (target) { framingSteps += 1; framingHistory.push({ step, targetId }); const framingPoint = midpoint(add(plan.origin, vector(0, cameraProfile.follow.lookAtHeight, 0)), target.targetPoint); lastFramingPoint = framingPoint; finalSelectedPoint = { ...target.targetPoint }; const desiredYaw = yawFromDirection(subtract(target.targetPoint, plan.origin)); const desiredPosition = boomPosition(plan.origin, desiredYaw, cameraProfile); cameraPosition = smoothVector(cameraPosition, desiredPosition, plan.fixedDeltaSeconds, cameraProfile.follow.positionHalfLifeSeconds); const desiredDirection = subtract(framingPoint, cameraPosition); const desiredOrientationYaw = yawFromDirection(desiredDirection); const desiredPitch = clamp(-Math.atan2(desiredDirection.y, Math.hypot(desiredDirection.x, desiredDirection.z)) * 180 / Math.PI, cameraProfile.orbit.minimumPitchDegrees, cameraProfile.orbit.maximumPitchDegrees); const errorBefore = angularError(cameraYaw, cameraPitch, desiredDirection); if (initialFramingError === null) initialFramingError = errorBefore; maximumFramingError = Math.max(maximumFramingError, errorBefore); cameraYaw = smoothYaw(cameraYaw, desiredOrientationYaw, plan.fixedDeltaSeconds, cameraProfile.follow.rotationHalfLifeSeconds); cameraPitch = smoothScalar(cameraPitch, desiredPitch, plan.fixedDeltaSeconds, cameraProfile.follow.rotationHalfLifeSeconds); finalFramingError = angularError(cameraYaw, cameraPitch, desiredDirection); } }
  }
  const finalContext = measuredContext(plan, candidates, targetId); latestEvaluations = runtimeEvaluations(profile, finalContext); const postReleaseTranslation = releaseCamera ? distance(cameraPosition, releaseCamera.position) : 0; const postReleaseAngular = releaseCamera ? Math.hypot(shortestAngleDifferenceDegrees(releaseCamera.yaw, cameraYaw), cameraPitch - releaseCamera.pitch) : 0;
  return { scenario: plan.id, metrics: rounded({ initialTargetId: plan.initialTargetId, selectedTargetId, finalTargetId: targetId, targetIdHistory: targetHistory, lockState: targetId === null ? "unlocked" : "locked", tieBreakResult, candidateEvaluations: latestEvaluations, graceStartStep, graceStartTimeSeconds: time(graceStartStep), graceExpiryStep, graceExpiryTimeSeconds: time(graceExpiryStep), releaseStep, releaseTimeSeconds: time(releaseStep), reacquiredTargetId, autoReacquire: profile.retention.autoReacquire, switchRequests, framingActive: targetId !== null, framingActivePhysicsSteps: framingSteps, framingTargetIdHistory: framingHistory, initialCameraYawDegrees: initialCameraYaw, finalCameraYawDegrees: cameraYaw, initialCameraPitchDegrees: initialCameraPitch, finalCameraPitchDegrees: cameraPitch, initialFramingAngularErrorDegrees: initialFramingError, maximumFramingAngularErrorDegrees: maximumFramingError, finalFramingAngularErrorDegrees: finalFramingError, finalCameraPosition: cameraPosition, finalFramingPoint: lastFramingPoint, finalSelectedTargetPoint: finalSelectedPoint, cameraTranslationAfterRelease: postReleaseTranslation, cameraAngularMovementAfterReleaseDegrees: postReleaseAngular, physicsSteps: steps, fixedDeltaSeconds: plan.fixedDeltaSeconds, lens: { fieldOfViewDegrees: cameraProfile.lens.fieldOfViewDegrees, nearClipDistance: cameraProfile.lens.nearClipDistance, farClipDistance: cameraProfile.lens.farClipDistance } }) };

  function setTarget(value: string | null, step: number): void { if (targetId === value) return; targetId = value; targetHistory.push({ step, targetId: value }); }
  function time(step: number | null): number | null { return step === null ? null : step * plan.fixedDeltaSeconds; }
}

function runtimeEvaluations(profile: TargetingProfile, context: TargetingContext): Array<TargetEvaluation & { targetPoint: TargetingVector3; targetable: boolean; lineOfSight: boolean }> { return context.candidates.map((candidate) => ({ ...evaluateCandidate(profile, context, candidate), targetPoint: { ...candidate.targetPoint }, targetable: candidate.targetable, lineOfSight: candidate.lineOfSight })); }

function measuredContext(plan: TargetingRuntimeScenarioRequest, candidates: Map<string, TargetingRuntimeCandidate>, currentTargetId: string | null): TargetingContext { return { origin: plan.origin, viewForward: plan.viewForward, currentTargetId, candidates: [...candidates.values()].map((item): TargetCandidate => ({ id: item.id, targetPoint: item.targetPoint, targetable: item.targetable, priority: item.priority, lineOfSight: item.obstruction === "none" })) }; }
function boomPosition(origin: TargetingVector3, yaw: number, camera: CameraProfile): TargetingVector3 { const radians = yaw * Math.PI / 180; const forward = vector(-Math.sin(radians), 0, -Math.cos(radians)); const right = vector(Math.cos(radians), 0, -Math.sin(radians)); return add(add(subtract(origin, scale(forward, camera.follow.distance)), scale(right, camera.follow.shoulderOffset)), vector(0, camera.follow.height, 0)); }
function yawFromDirection(value: TargetingVector3): number { return normalizeYawDegrees(Math.atan2(-value.x, -value.z) * 180 / Math.PI); }
function smoothVector(current: TargetingVector3, target: TargetingVector3, delta: number, halfLife: number): TargetingVector3 { const remaining = halfLifeRemainingFraction(delta, halfLife); return add(target, scale(subtract(current, target), remaining)); }
function smoothScalar(current: number, target: number, delta: number, halfLife: number): number { return target + (current - target) * halfLifeRemainingFraction(delta, halfLife); }
function smoothYaw(current: number, target: number, delta: number, halfLife: number): number { return normalizeYawDegrees(target - shortestAngleDifferenceDegrees(current, target) * halfLifeRemainingFraction(delta, halfLife)); }
function angularError(yaw: number, pitch: number, desired: TargetingVector3): number { const radiansYaw = yaw * Math.PI / 180; const radiansPitch = pitch * Math.PI / 180; const forward = vector(-Math.sin(radiansYaw) * Math.cos(radiansPitch), -Math.sin(radiansPitch), -Math.cos(radiansYaw) * Math.cos(radiansPitch)); return Math.acos(clamp(dot(forward, desired) / (magnitude(forward) * magnitude(desired)), -1, 1)) * 180 / Math.PI; }
function midpoint(left: TargetingVector3, right: TargetingVector3): TargetingVector3 { return scale(add(left, right), 0.5); }
function add(left: TargetingVector3, right: TargetingVector3): TargetingVector3 { return vector(left.x + right.x, left.y + right.y, left.z + right.z); }
function subtract(left: TargetingVector3, right: TargetingVector3): TargetingVector3 { return vector(left.x - right.x, left.y - right.y, left.z - right.z); }
function scale(value: TargetingVector3, amount: number): TargetingVector3 { return vector(value.x * amount, value.y * amount, value.z * amount); }
function vector(x: number, y: number, z: number): TargetingVector3 { return { x, y, z }; }
function magnitude(value: TargetingVector3): number { return Math.hypot(value.x, value.y, value.z); }
function distance(left: TargetingVector3, right: TargetingVector3): number { return magnitude(subtract(left, right)); }
function dot(left: TargetingVector3, right: TargetingVector3): number { return left.x * right.x + left.y * right.y + left.z * right.z; }
function clamp(value: number, minimum: number, maximum: number): number { return Math.min(maximum, Math.max(minimum, value)); }
function rounded<T>(value: T): T { return deep(value) as T; }
function deep(value: unknown): unknown { if (typeof value === "number") return roundMetric(value); if (Array.isArray(value)) return value.map(deep); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, deep(item)])); return value; }
