import { randomUUID } from "node:crypto";
import { stat } from "node:fs/promises";
import path from "node:path";

import { simulateEncounter } from "../../domain/encounter/encounterSimulation";
import type { EncounterScenario, EncounterSimulation } from "../../domain/encounter/encounterTypes";
import { ENCOUNTER_FIXTURE_ID, RUNTIME_RUN_COMMAND, RUNTIME_SCHEMA_VERSION, type EncounterRuntimeRequest, type RuntimeResponse } from "../../domain/runtime/runtimeProtocol";
import { validateRuntimeRequest, validateRuntimeResponse } from "../../domain/runtime/runtimeValidation";
import { captureWorkspaceState, diffFileStates } from "../../infrastructure/files/changedFileAudit";
import { fileExists } from "../../infrastructure/files/jsonFileStore";
import { discoverGodot, GodotDiscoveryError, type GodotExecutable } from "../../infrastructure/runtime/godotDiscovery";
import { runGodotProcess, type ProcessRunnerOptions } from "../../infrastructure/runtime/godotProcessRunner";
import { createRuntimeSession, readSessionJson, removeRuntimeSession, writeSessionJson, type RuntimeSession } from "../../infrastructure/runtime/runtimeSessionStore";
import { ErrorCodes } from "../../shared/errorCodes";
import type { LoadedEncounterBundle } from "../encounter/encounterOperationSupport";
import { RuntimeFixtureError } from "./runMovementFixture";

export interface RunEncounterFixtureOptions extends ProcessRunnerOptions { godot?: string; keepSession?: boolean; timeoutMs?: number }
export interface EncounterRuntimeFixtureExecution { executable: GodotExecutable; request: EncounterRuntimeRequest; readiness: RuntimeResponse; response: RuntimeResponse; process: Awaited<ReturnType<typeof runGodotProcess>>; simulation: EncounterSimulation; session: { retained: boolean; path: string | null }; runtimeSession: RuntimeSession; internalArtifacts: string[] }

export async function runEncounterFixture(workspaceRoot: string, loaded: LoadedEncounterBundle, scenario: EncounterScenario, fixedDeltaSeconds: number, options: RunEncounterFixtureOptions = {}): Promise<EncounterRuntimeFixtureExecution> {
  const before = await captureWorkspaceState(workspaceRoot); let executable: GodotExecutable; try { executable = await discoverGodot(options.godot); } catch (caught) { if (caught instanceof GodotDiscoveryError) throw new RuntimeFixtureError(caught.code, caught.message); throw caught; }
  const projectPath = path.join(workspaceRoot, "runtime", "godot"); try { if (!(await stat(path.join(projectPath, "project.godot"))).isFile()) throw new Error(); } catch { throw new RuntimeFixtureError(ErrorCodes.RuntimeProjectNotFound, "Godot runtime project was not found"); }
  const simulation = simulateEncounter({ profile: loaded.profile, resolvedDefinitionPaths: loaded.resolvedDefinitionPaths, arena: loaded.arena.profile, hunterHealth: loaded.hunter.health, hunterStamina: loaded.hunter.stamina, weapon: loaded.weapon, enemy: loaded.enemy.profile, enemyResolvedDefinitionPaths: loaded.enemy.resolvedDefinitionPaths, enemyHealth: loaded.enemy.health, enemyReaction: loaded.enemy.reaction, selectedBodyPartId: loaded.selectedBodyPartId, selectedHurtbox: loaded.selectedHurtbox, scenario, fixedDeltaSeconds });
  const cycleSeconds = loaded.enemy.profile.idleDurationSeconds + loaded.enemy.profile.telegraphDurationSeconds + loaded.enemy.profile.attackDurationSeconds + loaded.enemy.profile.recoveryDurationSeconds; const durationSeconds = Math.min(60, Math.max(fixedDeltaSeconds, simulation.enemyBehaviorCyclesCompleted * (cycleSeconds + loaded.weapon.offensiveAction.durationSeconds + loaded.weapon.offensiveAction.cooldownSeconds + Math.max(loaded.enemy.reaction.hitReactionDurationSeconds, loaded.enemy.reaction.staggerDurationSeconds))));
  const correlationId = randomUUID(); const request: EncounterRuntimeRequest = { schemaVersion: RUNTIME_SCHEMA_VERSION, commandId: RUNTIME_RUN_COMMAND, fixtureId: ENCOUNTER_FIXTURE_ID, correlationId, requestedAt: new Date().toISOString(), timeoutMs: Math.min(Math.max(options.timeoutMs ?? 30_000, 1), 60_000), payload: {
    encounterDefinitionKind: "encounter-profile", encounterDefinitionSchemaVersion: 1, encounterProfile: loaded.profile, resolvedDefinitionPaths: loaded.resolvedDefinitionPaths,
    hunterDefinitionKind: "hunter-profile", hunterDefinitionSchemaVersion: 1, hunterProfile: loaded.hunter.profile, hunterResolvedDefinitionPaths: loaded.hunter.resolvedDefinitionPaths, hunterHealthDefinitionKind: "health-profile", hunterHealthDefinitionSchemaVersion: 1, hunterHealthProfile: loaded.hunter.health, staminaDefinitionKind: "stamina-profile", staminaDefinitionSchemaVersion: 1, staminaProfile: loaded.hunter.stamina,
    weaponDefinitionKind: "weapon-profile", weaponDefinitionSchemaVersion: 1, weaponProfile: loaded.weapon.profile, weaponResolvedDefinitionPaths: loaded.weapon.resolvedDefinitionPaths, offensiveActionDefinitionKind: "offensive-action-profile", offensiveActionDefinitionSchemaVersion: 1, offensiveActionProfile: loaded.weapon.offensiveAction, actionTimelineDefinitionKind: "action-timeline-profile", actionTimelineDefinitionSchemaVersion: 1, actionTimelineProfile: loaded.weapon.actionTimeline, hitboxDefinitionKind: "contact-volume-profile", hitboxDefinitionSchemaVersion: 1, hitboxProfile: loaded.weapon.hitbox,
    enemyDefinitionKind: "large-enemy-profile", enemyDefinitionSchemaVersion: 1, enemyProfile: loaded.enemy.profile, enemyResolvedDefinitionPaths: loaded.enemy.resolvedDefinitionPaths, enemyHealthDefinitionKind: "health-profile", enemyHealthDefinitionSchemaVersion: 1, enemyHealthProfile: loaded.enemy.health, reactionDefinitionKind: "damage-reaction-profile", reactionDefinitionSchemaVersion: 1, reactionProfile: loaded.enemy.reaction, hurtboxDefinitionKind: "contact-volume-profile", hurtboxDefinitionSchemaVersion: 1, hurtboxProfiles: loaded.enemy.hurtboxes, selectedBodyPartId: loaded.selectedBodyPartId, selectedHurtboxProfile: loaded.selectedHurtbox,
    arenaDefinitionKind: "arena-profile", arenaDefinitionSchemaVersion: 1, arenaProfile: loaded.arena.profile, scenario: { id: scenario, durationSeconds, fixedDeltaSeconds, startingStamina: simulation.hunterStartingStamina }
  } };
  const requestValidation = validateRuntimeRequest(request); if (!requestValidation.valid) throw new RuntimeFixtureError(ErrorCodes.RuntimeRequestInvalid, "Encounter runtime request validation failed", null, { errors: requestValidation.errors });
  const session = await createRuntimeSession(workspaceRoot, correlationId); await writeSessionJson(session.requestPath, request); await writeSessionJson(session.metadataPath, { correlationId, state: "created", fixtureId: ENCOUNTER_FIXTURE_ID, executableSource: executable.source, requestedAt: request.requestedAt });
  try {
    let processResult: Awaited<ReturnType<typeof runGodotProcess>>; try { processResult = await runGodotProcess(executable.path, projectPath, session, { ...options, executionTimeoutMs: Math.min(options.executionTimeoutMs ?? 45_000, 60_000) }); } catch (caught) { throw new RuntimeFixtureError(ErrorCodes.RuntimeStartFailed, caught instanceof Error ? caught.message : String(caught), session); }
    if (processResult.timedOut) throw new RuntimeFixtureError(ErrorCodes.RuntimeTimeout, "Godot encounter runtime exceeded its deadline and was terminated", session, { process: processResult }); if (!processResult.readyObserved) throw new RuntimeFixtureError(ErrorCodes.RuntimeNotReady, "Godot exited before writing encounter readiness", session, { process: processResult });
    let readyValue: unknown; try { readyValue = await readSessionJson(session.readyPath); } catch { throw new RuntimeFixtureError(ErrorCodes.RuntimeResponseInvalid, "Godot readiness file is missing or malformed", session); } const ready = validateRuntimeResponse(readyValue, { correlationId, fixtureId: ENCOUNTER_FIXTURE_ID, commandId: "runtime.fixture.ready", status: "ready" }); if (!ready.valid || !ready.value) throw responseValidationError(ready.errors, "readiness", session);
    if (processResult.exitCode !== 0) throw new RuntimeFixtureError(ErrorCodes.RuntimeProcessExited, `Godot exited with code ${processResult.exitCode ?? "unknown"}`, session, { process: processResult }); if (!await fileExists(session.responsePath)) throw new RuntimeFixtureError(ErrorCodes.RuntimeResponseMissing, "Godot encounter final response is missing", session);
    let responseValue: unknown; try { responseValue = await readSessionJson(session.responsePath); } catch { throw new RuntimeFixtureError(ErrorCodes.RuntimeResponseInvalid, "Godot encounter response contains malformed JSON", session); } const response = validateRuntimeResponse(responseValue, { correlationId, fixtureId: ENCOUNTER_FIXTURE_ID, commandId: RUNTIME_RUN_COMMAND, status: ["ok", "rejected", "failed"], scenarioId: scenario }); if (!response.valid || !response.value) throw responseValidationError(response.errors, "response", session); if (response.value.status !== "ok") throw new RuntimeFixtureError(ErrorCodes.RuntimeExecutionFailed, `Godot encounter runtime returned ${response.value.status}`, session, { validationErrors: response.value.validationErrors, runtimeErrors: response.value.runtimeErrors });
    const changed = diffFileStates(before, await captureWorkspaceState(workspaceRoot)); const internalArtifacts = changed.filter(isAllowedRuntimeArtifact); const unexpected = changed.filter((file) => !isAllowedRuntimeArtifact(file)); if (unexpected.length > 0) throw new RuntimeFixtureError(ErrorCodes.RuntimeUnexpectedFileChange, "Godot encounter runtime changed files outside its allowlist", session, { unexpectedFiles: unexpected });
    const retain = options.keepSession === true; if (!retain) await removeRuntimeSession(session); return { executable, request, readiness: ready.value, response: response.value, process: processResult, simulation, session: { retained: retain, path: retain ? session.relativeDirectory : null }, runtimeSession: session, internalArtifacts };
  } catch (caught) { await writeSessionJson(session.metadataPath, { correlationId, state: "failed", code: caught instanceof RuntimeFixtureError ? caught.code : ErrorCodes.RuntimeExecutionFailed }).catch(() => undefined); if (caught instanceof RuntimeFixtureError) throw caught; throw new RuntimeFixtureError(ErrorCodes.RuntimeExecutionFailed, caught instanceof Error ? caught.message : String(caught), session); }
}
function responseValidationError(errors: string[], label: string, session: RuntimeSession): RuntimeFixtureError { const joined = errors.join(", "); const code = joined.includes("protocol") ? ErrorCodes.RuntimeProtocolMismatch : joined.includes("correlation") ? ErrorCodes.RuntimeCorrelationMismatch : joined.includes("fixture") ? ErrorCodes.RuntimeFixtureMismatch : ErrorCodes.RuntimeResponseInvalid; return new RuntimeFixtureError(code, `Encounter runtime ${label} validation failed`, session, { errors }); }
function isAllowedRuntimeArtifact(file: string): boolean { return file.startsWith(".mam-engine/runtime-sessions/") || file.startsWith("runtime/godot/.godot/"); }
