import type { StaminaCombatRuntimeScenario } from "../../domain/runtime/runtimeProtocol";
import { removeRuntimeSession } from "../../infrastructure/runtime/runtimeSessionStore";
import { ErrorCodes } from "../../shared/errorCodes";
import { operationResult, type OperationResult } from "../../shared/operationResult";
import { isLoadedHealth, loadValidHealth } from "../health/healthOperationSupport";
import { isLoadedOffensiveAction, loadValidOffensiveAction } from "../offensiveAction/offensiveActionOperationSupport";
import { isLoadedStamina, loadValidStamina } from "../stamina/staminaOperationSupport";
import { runtimeFailure } from "./checkRuntime";
import { compareStaminaCombatRuntime } from "./compareStaminaCombatRuntime";
import { runStaminaCombatFixture, type RunStaminaCombatFixtureOptions } from "./runStaminaCombatFixture";

export async function runStaminaCombatRuntimeTest(workspaceRoot: string, staminaFile: string, healthFile: string, offensiveActionFile: string, scenario: StaminaCombatRuntimeScenario, options: RunStaminaCombatFixtureOptions = {}): Promise<OperationResult> {
  const command = "combat.stamina-runtime-test"; const input = { staminaFile, healthFile, offensiveActionFile, scenario }; const stamina = await loadValidStamina(workspaceRoot, staminaFile); if (!isLoadedStamina(stamina)) return operationResult({ command, status: "failed", input, errors: stamina.errors }); const health = await loadValidHealth(workspaceRoot, healthFile); if (!isLoadedHealth(health)) return operationResult({ command, status: "failed", input: { ...input, staminaFile: stamina.relativePath }, errors: health.errors }); const action = await loadValidOffensiveAction(workspaceRoot, offensiveActionFile); if (!isLoadedOffensiveAction(action)) return operationResult({ command, status: "failed", input: { ...input, staminaFile: stamina.relativePath, healthFile: health.relativePath }, errors: action.errors });
  try { const run = await runStaminaCombatFixture(workspaceRoot, stamina.profile, health.profile, action.profile, scenario, { ...options, keepSession: true }); const comparison = compareStaminaCombatRuntime(run.simulation, run.response.metrics); if (comparison.passed && options.keepSession !== true) { await removeRuntimeSession(run.runtimeSession); run.session = { retained: false, path: null }; } const data = { runtime: { fixtureId: run.request.fixtureId, scenarioId: scenario, godotVersion: run.executable.version.reportedVersion, metrics: run.response.metrics, evidence: run.response.evidence, process: run.process }, simulation: run.simulation, comparison, session: run.session, internalArtifacts: run.internalArtifacts }; if (!comparison.passed) return operationResult({ command, status: "failed", input: { ...input, staminaFile: stamina.relativePath, healthFile: health.relativePath, offensiveActionFile: action.relativePath }, data, errors: [{ code: ErrorCodes.RuntimeMetricToleranceExceeded, message: "Stamina combat runtime metrics differ from the TypeScript simulation", details: { failedMetrics: comparison.metrics.filter((metric) => !metric.passed) } }] }); return operationResult({ command, status: "passed", input: { ...input, staminaFile: stamina.relativePath, healthFile: health.relativePath, offensiveActionFile: action.relativePath }, data }); } catch (caught) { return runtimeFailure(command, caught, input); }
}
