import type { StaminaActionProfile } from "../../domain/stamina/staminaTypes";
import { removeRuntimeSession } from "../../infrastructure/runtime/runtimeSessionStore";
import { ErrorCodes } from "../../shared/errorCodes";
import { operationResult, type OperationResult } from "../../shared/operationResult";
import { isLoadedDefinition, loadValidDefinition } from "../definitions/loadValidDefinition";
import { isLoadedStamina, loadValidStamina } from "../stamina/staminaOperationSupport";
import { runtimeFailure } from "./checkRuntime";
import { compareStaminaRuntime } from "./compareStaminaRuntime";
import { runStaminaFixture, type RunStaminaFixtureOptions } from "./runStaminaFixture";

export async function runStaminaRuntimeTest(workspaceRoot: string, staminaFile: string, actionFile: string, options: RunStaminaFixtureOptions = {}): Promise<OperationResult> {
  const command = "stamina.runtime-test"; const input = { staminaFile, actionFile }; const stamina = await loadValidStamina(workspaceRoot, staminaFile); if (!isLoadedStamina(stamina)) return operationResult({ command, status: "failed", input, errors: stamina.errors }); const action = await loadValidDefinition(workspaceRoot, actionFile); if (!isLoadedDefinition(action)) return operationResult({ command, status: "failed", input: { ...input, staminaFile: stamina.relativePath }, errors: action.errors }); if (action.kind !== "offensive-action-profile" && action.kind !== "defensive-action-profile") return operationResult({ command, status: "failed", input: { staminaFile: stamina.relativePath, actionFile: action.relativePath }, errors: [{ code: ErrorCodes.DefinitionKindUnsupported, path: "kind", message: "Stamina runtime requires an offensive-action-profile or defensive-action-profile", actual: action.kind, expected: ["offensive-action-profile", "defensive-action-profile"] }] });
  try { const run = await runStaminaFixture(workspaceRoot, stamina.profile, action.definition as StaminaActionProfile, { ...options, keepSession: true }); const comparison = compareStaminaRuntime(run.simulation, run.response.metrics); if (comparison.passed && options.keepSession !== true) { await removeRuntimeSession(run.runtimeSession); run.session = { retained: false, path: null }; } const data = { runtime: { fixtureId: run.request.fixtureId, scenarioId: "action-cost", godotVersion: run.executable.version.reportedVersion, metrics: run.response.metrics, evidence: run.response.evidence, process: run.process }, simulation: run.simulation, comparison, session: run.session, internalArtifacts: run.internalArtifacts }; if (!comparison.passed) return operationResult({ command, status: "failed", input: { staminaFile: stamina.relativePath, actionFile: action.relativePath }, data, errors: [{ code: ErrorCodes.RuntimeMetricToleranceExceeded, message: "Stamina runtime metrics differ from the TypeScript simulation", details: { failedMetrics: comparison.metrics.filter((metric) => !metric.passed) } }] }); return operationResult({ command, status: "passed", input: { staminaFile: stamina.relativePath, actionFile: action.relativePath }, data }); } catch (caught) { return runtimeFailure(command, caught, input); }
}
