import type { WeaponRuntimeScenario } from "../../domain/runtime/runtimeProtocol";
import { WEAPON_FIXED_DELTA_SECONDS } from "../../domain/weapon/weaponSimulation";
import { removeRuntimeSession } from "../../infrastructure/runtime/runtimeSessionStore";
import { ErrorCodes } from "../../shared/errorCodes";
import { operationResult, type OperationResult } from "../../shared/operationResult";
import { isLoadedContactVolume, loadValidContactVolume } from "../contactVolume/contactVolumeOperationSupport";
import { isLoadedDamageReaction, loadValidDamageReaction } from "../damageReaction/damageReactionOperationSupport";
import { isLoadedHealth, loadValidHealth } from "../health/healthOperationSupport";
import { isLoadedStamina, loadValidStamina } from "../stamina/staminaOperationSupport";
import { isLoadedWeaponBundle, loadValidWeaponBundle } from "../weapon/weaponOperationSupport";
import { runtimeFailure } from "./checkRuntime";
import { compareWeaponRuntime } from "./compareWeaponRuntime";
import { runWeaponFixture, type RunWeaponFixtureOptions } from "./runWeaponFixture";

export async function runWeaponRuntimeTest(workspaceRoot: string, weaponFile: string, staminaFile: string, healthFile: string, hurtboxFile: string, reactionFile: string, scenario: WeaponRuntimeScenario, fixedDelta = WEAPON_FIXED_DELTA_SECONDS, options: RunWeaponFixtureOptions = {}): Promise<OperationResult> {
  const command = "weapon.runtime-test"; const input = { weaponFile, staminaFile, healthFile, hurtboxFile, reactionFile, scenario, fixedDelta };
  if (!Number.isFinite(fixedDelta) || fixedDelta <= 0 || fixedDelta > 1) return operationResult({ command, status: "failed", input, errors: [{ code: ErrorCodes.CliArgumentInvalid, path: "fixedDelta", message: "fixed delta must be finite, greater than zero, and at most 1", actual: fixedDelta, expected: "(0, 1]" }] });
  const weapon = await loadValidWeaponBundle(workspaceRoot, weaponFile); if (!isLoadedWeaponBundle(weapon)) return operationResult({ command, status: "failed", input, errors: weapon.errors }); const stamina = await loadValidStamina(workspaceRoot, staminaFile); if (!isLoadedStamina(stamina)) return operationResult({ command, status: "failed", input, errors: stamina.errors }); const health = await loadValidHealth(workspaceRoot, healthFile); if (!isLoadedHealth(health)) return operationResult({ command, status: "failed", input, errors: health.errors }); const hurtbox = await loadValidContactVolume(workspaceRoot, hurtboxFile); if (!isLoadedContactVolume(hurtbox)) return operationResult({ command, status: "failed", input, errors: hurtbox.errors }); if (hurtbox.profile.role !== "hurtbox") return operationResult({ command, status: "failed", input, errors: [{ code: ErrorCodes.ContactVolumeRoleInvalid, path: hurtbox.relativePath, message: "Weapon runtime target contact volume must have role hurtbox", actual: hurtbox.profile.role, expected: "hurtbox" }] }); const reaction = await loadValidDamageReaction(workspaceRoot, reactionFile); if (!isLoadedDamageReaction(reaction)) return operationResult({ command, status: "failed", input, errors: reaction.errors });
  try { const run = await runWeaponFixture(workspaceRoot, weapon.profile, weapon.resolvedDefinitionPaths, stamina.profile, health.profile, hurtbox.profile, reaction.profile, weapon.offensiveAction, weapon.actionTimeline, weapon.hitbox, scenario, fixedDelta, { ...options, keepSession: true }); const comparison = compareWeaponRuntime(run.simulation, run.response.metrics); if (comparison.passed && options.keepSession !== true) { await removeRuntimeSession(run.runtimeSession); run.session = { retained: false, path: null }; } const data = { runtime: { fixtureId: run.request.fixtureId, scenarioId: scenario, godotVersion: run.executable.version.reportedVersion, metrics: run.response.metrics, evidence: run.response.evidence, process: run.process }, simulation: run.simulation, comparison, session: run.session, internalArtifacts: run.internalArtifacts }; if (!comparison.passed) return operationResult({ command, status: "failed", input, data, errors: [{ code: ErrorCodes.RuntimeMetricToleranceExceeded, message: "Weapon runtime metrics differ from the TypeScript simulation", details: { failedMetrics: comparison.metrics.filter((metric) => !metric.passed) } }] }); return operationResult({ command, status: "passed", input: { ...input, weaponFile: weapon.relativePath, staminaFile: stamina.relativePath, healthFile: health.relativePath, hurtboxFile: hurtbox.relativePath, reactionFile: reaction.relativePath }, data }); } catch (caught) { return runtimeFailure(command, caught, input); }
}
