import assert from "node:assert/strict";
import { rm } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import type { TargetingRuntimeScenario } from "../../src/domain/runtime/targetingRuntimePlan";
import { runTargetingRuntimeTest } from "../../src/application/runtime/runTargetingRuntimeTest";
import { runTargetingFixture } from "../../src/application/runtime/runTargetingFixture";
import { compareTargetingRuntime } from "../../src/application/runtime/compareTargetingRuntime";
import { discoverGodot } from "../../src/infrastructure/runtime/godotDiscovery";
import { defaultCameraProfile, defaultTargetingProfile, projectRoot } from "../testUtils";

const availability = discoverGodot().then(() => null, (error: Error) => error.message);
const scenarios: TargetingRuntimeScenario[] = ["acquire", "eligibility", "tie-break", "retention", "loss", "reacquire", "switch-left", "switch-right", "switch-cooldown", "framing-acquire", "framing-switch", "framing-loss", "framing-reacquire"];
test("real Godot targeting cold-cache readiness", async (context) => { const reason = await availability; if (reason) { context.skip(`Godot unavailable: ${reason}`); return; } await rm(path.join(projectRoot(), "runtime", "godot", ".godot"), { recursive: true, force: true }); const result = await runTargetingRuntimeTest(projectRoot(), "examples/targeting/default.json", "examples/camera/default.json", "acquire"); assert.equal(result.status, "passed", JSON.stringify(result)); });
for (const scenario of scenarios) test(`real Godot targeting ${scenario} matches the reference simulation`, async (context) => { const reason = await availability; if (reason) { context.skip(`Godot unavailable: ${reason}`); return; } const result = await runTargetingRuntimeTest(projectRoot(), "examples/targeting/default.json", "examples/camera/default.json", scenario); assert.equal(result.status, "passed", JSON.stringify(result)); assert.deepEqual(result.changedFiles, []); assert.equal((result.data as any).runtime.fixtureId, "targeting/basic-lock-on"); assert.equal((result.data as any).runtime.process.exitCode, 0); assert.equal((result.data as any).session.retained, false); });
test("real Godot targeting respects disabled automatic reacquisition", async (context) => { const reason = await availability; if (reason) { context.skip(`Godot unavailable: ${reason}`); return; } const targeting = await defaultTargetingProfile(); targeting.retention.autoReacquire = false; const run = await runTargetingFixture(projectRoot(), targeting, await defaultCameraProfile(), "reacquire", undefined); assert.equal(compareTargetingRuntime(run.simulation, run.response.metrics).passed, true); assert.equal(run.response.metrics.finalTargetId, null); });
test("real Godot targeting snaps zero camera half-lives", async (context) => { const reason = await availability; if (reason) { context.skip(`Godot unavailable: ${reason}`); return; } const camera = await defaultCameraProfile(); camera.follow.positionHalfLifeSeconds = 0; camera.follow.rotationHalfLifeSeconds = 0; const run = await runTargetingFixture(projectRoot(), await defaultTargetingProfile(), camera, "framing-switch", undefined); assert.equal(compareTargetingRuntime(run.simulation, run.response.metrics).passed, true); });
test("real Godot targeting clamps camera pitch and reads back lens", async (context) => { const reason = await availability; if (reason) { context.skip(`Godot unavailable: ${reason}`); return; } const camera = await defaultCameraProfile(); camera.orbit.minimumPitchDegrees = -1; camera.orbit.maximumPitchDegrees = 1; camera.orbit.initialPitchDegrees = 0; const run = await runTargetingFixture(projectRoot(), await defaultTargetingProfile(), camera, "framing-acquire", undefined); assert.equal(compareTargetingRuntime(run.simulation, run.response.metrics).passed, true); assert(Math.abs(Number(run.response.metrics.finalCameraPitchDegrees)) <= 1.001); assert(Math.abs(Number((run.response.metrics.lens as any).fieldOfViewDegrees) - camera.lens.fieldOfViewDegrees) <= 0.001); });
