import type { WeaponProfile } from "../../domain/weapon/weaponTypes";
import { validateWeaponDefinition } from "../../domain/weapon/weaponValidation";
import { auditChangedFiles, captureWorkspaceState, resolveWorkspacePath } from "../../infrastructure/files/changedFileAudit";
import { formatJson } from "../../infrastructure/files/jsonFileStore";
import { createFileSnapshot, type CreatedSnapshot } from "../../infrastructure/snapshots/fileSnapshotStore";
import { ErrorCodes } from "../../shared/errorCodes";
import { operationResult, type OperationError, type OperationResult } from "../../shared/operationResult";
import { transactionalFileReplace, type ContentVerification, type TransactionalFileReplaceDependencies, type TransactionalReplaceFailure } from "../persistence/transactionalFileReplace";
import { withTargetOperationLock } from "../persistence/targetOperationLock";
import { isLoadedWeapon, isResolvedWeaponReferences, loadValidWeapon, resolveWeaponReferences } from "./weaponOperationSupport";

export interface SetWeaponValueDependencies { createSnapshot: typeof createFileSnapshot; transaction: Partial<TransactionalFileReplaceDependencies>; verifyContent: (content: string) => ContentVerification<WeaponProfile> }
const productionDependencies: SetWeaponValueDependencies = { createSnapshot: createFileSnapshot, transaction: {}, verifyContent: verifyWeaponContent };

export async function setWeaponValue(workspaceRoot: string, inputFile: string, propertyPath: string, value: unknown, dryRun: boolean, injected: Partial<SetWeaponValueDependencies> = {}): Promise<OperationResult> { const dependencies = { ...productionDependencies, ...injected, transaction: { ...productionDependencies.transaction, ...injected.transaction } }; if (dryRun) return executeSet(workspaceRoot, inputFile, propertyPath, value, true, dependencies); let relativePath: string; try { relativePath = resolveWorkspacePath(workspaceRoot, inputFile).relativePath; } catch (caught) { return operationResult({ command: "weapon.set", status: "failed", input: { file: inputFile, propertyPath, value, dryRun }, errors: [{ code: ErrorCodes.WeaponWriteBlocked, path: inputFile, message: caught instanceof Error ? caught.message : String(caught) }] }); } return withTargetOperationLock(workspaceRoot, relativePath, () => executeSet(workspaceRoot, inputFile, propertyPath, value, false, dependencies)); }

async function executeSet(workspaceRoot: string, inputFile: string, propertyPath: string, value: unknown, dryRun: boolean, dependencies: SetWeaponValueDependencies): Promise<OperationResult> {
  const command = "weapon.set"; const input = { file: inputFile, propertyPath, value, dryRun }; const before = await captureWorkspaceState(workspaceRoot); const loaded = await loadValidWeapon(workspaceRoot, inputFile); if (!isLoadedWeapon(loaded)) return operationResult({ command, status: "failed", input, errors: loaded.errors });
  const candidate = structuredClone(loaded.profile) as WeaponProfile; const pathError = applyExistingProperty(candidate, propertyPath, value); if (pathError) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: [pathError] });
  const validation = validateWeaponDefinition(candidate); if (!validation.valid || validation.profile === null) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: validation.errors.map((error) => error.code === ErrorCodes.WeaponSchemaInvalid ? { ...error, code: ErrorCodes.WeaponPropertyValueInvalid } : error) });
  const references = await resolveWeaponReferences(workspaceRoot, validation.profile); if (!isResolvedWeaponReferences(references)) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: references.errors });
  if (dryRun) { const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); if (!audit.ok) return operationResult({ command, status: "failed", input, errors: [{ code: ErrorCodes.WeaponWriteScopeAuditFailed, message: "Weapon dry run changed files outside its zero-write scope", details: { unexpectedFiles: audit.unexpectedFiles } }], changedFiles: audit.changedFiles }); return operationResult({ command, status: "dry_run", input: { ...input, file: loaded.relativePath }, data: { profile: validation.profile, resolvedDefinitionPaths: references.resolvedDefinitionPaths, proposedChange: { path: propertyPath, value } } }); }
  let snapshot: CreatedSnapshot; try { snapshot = await dependencies.createSnapshot(workspaceRoot, loaded.relativePath, loaded.content, command, "weapon-profile"); } catch (caught) { const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: [{ code: ErrorCodes.WeaponWriteBlocked, path: loaded.relativePath, message: `Pre-write snapshot could not be created: ${caught instanceof Error ? caught.message : String(caught)}` }], changedFiles: audit.changedFiles }); }
  const transaction = await transactionalFileReplace({ workspaceRoot, operationStartState: before, targetAbsolutePath: loaded.absolutePath, targetRelativePath: loaded.relativePath, replacementContent: formatJson(validation.profile), originalContent: loaded.content, allowedPaths: [loaded.relativePath, snapshot.relativePath], verifyContent: dependencies.verifyContent, dependencies: dependencies.transaction }); if (!transaction.ok) return transactionFailure(command, { ...input, file: loaded.relativePath }, transaction, snapshot.record.snapshotId); return operationResult({ command, status: "passed", input: { ...input, file: loaded.relativePath }, data: { profile: transaction.value, resolvedDefinitionPaths: references.resolvedDefinitionPaths, appliedChange: { path: propertyPath, value } }, changedFiles: transaction.changedFiles, snapshotId: snapshot.record.snapshotId });
}

export function verifyWeaponContent(content: string): ContentVerification<WeaponProfile> { let value: unknown; try { value = JSON.parse(content) as unknown; } catch { return { validationPassed: false, errors: [{ code: ErrorCodes.WeaponJsonInvalid, message: "Persisted weapon content is not valid JSON" }] }; } const validation = validateWeaponDefinition(value); return validation.valid && validation.profile ? { validationPassed: true, value: validation.profile } : { validationPassed: false, errors: validation.errors }; }
function transactionFailure(command: string, input: Record<string, unknown>, transaction: TransactionalReplaceFailure, snapshotId: string): OperationResult { const errors: OperationError[] = [{ code: transaction.failureStage === "scope_audit" ? ErrorCodes.WeaponWriteScopeAuditFailed : ErrorCodes.WeaponWriteVerificationFailed, message: transaction.failureMessage, details: { failureStage: transaction.failureStage, unexpectedFiles: transaction.unexpectedFiles, verificationErrors: transaction.verificationErrors } }]; if (transaction.recovery.status === "failed") errors.push({ code: ErrorCodes.WeaponWriteRecoveryFailed, path: transaction.recovery.restoredFile, message: "Weapon write recovery could not verify the exact original target state", details: { recovery: transaction.recovery } }); return operationResult({ command, status: "failed", input, data: { failureStage: transaction.failureStage, recovery: transaction.recovery }, errors, changedFiles: transaction.changedFiles, snapshotId }); }
function applyExistingProperty(profile: WeaponProfile, propertyPath: string, value: unknown): OperationError | null { if (!propertyPath || propertyPath.includes(".") || ["__proto__", "prototype", "constructor"].includes(propertyPath) || !Object.prototype.hasOwnProperty.call(profile, propertyPath)) return { code: ErrorCodes.WeaponPropertyNotFound, path: propertyPath, message: "Only existing schema-defined weapon properties may be edited" }; (profile as unknown as Record<string, unknown>)[propertyPath] = value; return null; }
