import type { LargeEnemyProfile } from "../../domain/largeEnemy/largeEnemyTypes";
import { validateLargeEnemyDefinition } from "../../domain/largeEnemy/largeEnemyValidation";
import { auditChangedFiles, captureWorkspaceState, resolveWorkspacePath } from "../../infrastructure/files/changedFileAudit";
import { formatJson } from "../../infrastructure/files/jsonFileStore";
import { createFileSnapshot, type CreatedSnapshot } from "../../infrastructure/snapshots/fileSnapshotStore";
import { ErrorCodes } from "../../shared/errorCodes";
import { operationResult, type OperationError, type OperationResult } from "../../shared/operationResult";
import { transactionalFileReplace, type ContentVerification, type TransactionalFileReplaceDependencies, type TransactionalReplaceFailure } from "../persistence/transactionalFileReplace";
import { withTargetOperationLock } from "../persistence/targetOperationLock";
import { isLoadedLargeEnemy, isResolvedLargeEnemyReferences, loadValidLargeEnemy, resolveLargeEnemyReferences } from "./largeEnemyOperationSupport";

export interface SetLargeEnemyValueDependencies { createSnapshot: typeof createFileSnapshot; transaction: Partial<TransactionalFileReplaceDependencies>; verifyContent: (content: string) => ContentVerification<LargeEnemyProfile> }
const productionDependencies: SetLargeEnemyValueDependencies = { createSnapshot: createFileSnapshot, transaction: {}, verifyContent: verifyLargeEnemyContent };

export async function setLargeEnemyValue(workspaceRoot: string, inputFile: string, propertyPath: string, value: unknown, dryRun: boolean, injected: Partial<SetLargeEnemyValueDependencies> = {}): Promise<OperationResult> { const dependencies = { ...productionDependencies, ...injected, transaction: { ...productionDependencies.transaction, ...injected.transaction } }; if (dryRun) return executeSet(workspaceRoot, inputFile, propertyPath, value, true, dependencies); let relativePath: string; try { relativePath = resolveWorkspacePath(workspaceRoot, inputFile).relativePath; } catch (caught) { return operationResult({ command: "large-enemy.set", status: "failed", input: { file: inputFile, propertyPath, value, dryRun }, errors: [{ code: ErrorCodes.LargeEnemyWriteBlocked, path: inputFile, message: caught instanceof Error ? caught.message : String(caught) }] }); } return withTargetOperationLock(workspaceRoot, relativePath, () => executeSet(workspaceRoot, inputFile, propertyPath, value, false, dependencies)); }

async function executeSet(workspaceRoot: string, inputFile: string, propertyPath: string, value: unknown, dryRun: boolean, dependencies: SetLargeEnemyValueDependencies): Promise<OperationResult> {
  const command = "large-enemy.set"; const input = { file: inputFile, propertyPath, value, dryRun }; const before = await captureWorkspaceState(workspaceRoot); const loaded = await loadValidLargeEnemy(workspaceRoot, inputFile); if (!isLoadedLargeEnemy(loaded)) return operationResult({ command, status: "failed", input, errors: loaded.errors });
  const candidate = structuredClone(loaded.profile) as LargeEnemyProfile; const pathError = applyExistingProperty(candidate, propertyPath, value); if (pathError) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: [pathError] });
  const validation = validateLargeEnemyDefinition(candidate); if (!validation.valid || validation.profile === null) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: validation.errors.map((error) => error.code === ErrorCodes.LargeEnemySchemaInvalid ? { ...error, code: ErrorCodes.LargeEnemyPropertyValueInvalid } : error) });
  const references = await resolveLargeEnemyReferences(workspaceRoot, validation.profile); if (!isResolvedLargeEnemyReferences(references)) return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: references.errors });
  if (dryRun) { const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); if (!audit.ok) return operationResult({ command, status: "failed", input, errors: [{ code: ErrorCodes.LargeEnemyWriteScopeAuditFailed, message: "Large-enemy dry run changed files outside its zero-write scope", details: { unexpectedFiles: audit.unexpectedFiles } }], changedFiles: audit.changedFiles }); return operationResult({ command, status: "dry_run", input: { ...input, file: loaded.relativePath }, data: { profile: validation.profile, resolvedDefinitionPaths: references.resolvedDefinitionPaths, proposedChange: { path: propertyPath, value } } }); }
  let snapshot: CreatedSnapshot; try { snapshot = await dependencies.createSnapshot(workspaceRoot, loaded.relativePath, loaded.content, command, "large-enemy-profile"); } catch (caught) { const audit = auditChangedFiles(before, await captureWorkspaceState(workspaceRoot), []); return operationResult({ command, status: "failed", input: { ...input, file: loaded.relativePath }, errors: [{ code: ErrorCodes.LargeEnemyWriteBlocked, path: loaded.relativePath, message: `Pre-write snapshot could not be created: ${caught instanceof Error ? caught.message : String(caught)}` }], changedFiles: audit.changedFiles }); }
  const transaction = await transactionalFileReplace({ workspaceRoot, operationStartState: before, targetAbsolutePath: loaded.absolutePath, targetRelativePath: loaded.relativePath, replacementContent: formatJson(validation.profile), originalContent: loaded.content, allowedPaths: [loaded.relativePath, snapshot.relativePath], verifyContent: dependencies.verifyContent, dependencies: dependencies.transaction }); if (!transaction.ok) return transactionFailure(command, { ...input, file: loaded.relativePath }, transaction, snapshot.record.snapshotId); return operationResult({ command, status: "passed", input: { ...input, file: loaded.relativePath }, data: { profile: transaction.value, resolvedDefinitionPaths: references.resolvedDefinitionPaths, appliedChange: { path: propertyPath, value } }, changedFiles: transaction.changedFiles, snapshotId: snapshot.record.snapshotId });
}

export function verifyLargeEnemyContent(content: string): ContentVerification<LargeEnemyProfile> { let value: unknown; try { value = JSON.parse(content) as unknown; } catch { return { validationPassed: false, errors: [{ code: ErrorCodes.LargeEnemyJsonInvalid, message: "Persisted large-enemy content is not valid JSON" }] }; } const validation = validateLargeEnemyDefinition(value); return validation.valid && validation.profile ? { validationPassed: true, value: validation.profile } : { validationPassed: false, errors: validation.errors }; }
function transactionFailure(command: string, input: Record<string, unknown>, transaction: TransactionalReplaceFailure, snapshotId: string): OperationResult { const errors: OperationError[] = [{ code: transaction.failureStage === "scope_audit" ? ErrorCodes.LargeEnemyWriteScopeAuditFailed : ErrorCodes.LargeEnemyWriteVerificationFailed, message: transaction.failureMessage, details: { failureStage: transaction.failureStage, unexpectedFiles: transaction.unexpectedFiles, verificationErrors: transaction.verificationErrors } }]; if (transaction.recovery.status === "failed") errors.push({ code: ErrorCodes.LargeEnemyWriteRecoveryFailed, path: transaction.recovery.restoredFile, message: "Large-enemy write recovery could not verify the exact original target state", details: { recovery: transaction.recovery } }); return operationResult({ command, status: "failed", input, data: { failureStage: transaction.failureStage, recovery: transaction.recovery }, errors, changedFiles: transaction.changedFiles, snapshotId }); }

function applyExistingProperty(profile: LargeEnemyProfile, propertyPath: string, value: unknown): OperationError | null {
  const segments = propertyPath.split("."); if (!propertyPath || segments.some((segment) => !segment || ["__proto__", "prototype", "constructor"].includes(segment))) return notFound(propertyPath);
  let current: unknown = profile;
  for (const segment of segments.slice(0, -1)) { current = childAt(current, segment); if (current === undefined) return notFound(propertyPath); }
  const leaf = segments.at(-1) as string;
  if (Array.isArray(current)) { const index = arrayIndex(leaf, current.length); if (index === null) return notFound(propertyPath); current[index] = value; return null; }
  if (!record(current) || !Object.prototype.hasOwnProperty.call(current, leaf)) return notFound(propertyPath); current[leaf] = value; return null;
}
function childAt(value: unknown, segment: string): unknown { if (Array.isArray(value)) { const index = arrayIndex(segment, value.length); return index === null ? undefined : value[index]; } return record(value) && Object.prototype.hasOwnProperty.call(value, segment) ? value[segment] : undefined; }
function arrayIndex(segment: string, length: number): number | null { if (!/^(0|[1-9]\d*)$/.test(segment)) return null; const index = Number(segment); return index < length ? index : null; }
function notFound(path: string): OperationError { return { code: ErrorCodes.LargeEnemyPropertyNotFound, path, message: "Only existing schema-defined large-enemy properties may be edited" }; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
